kubernetes-sigs/cluster-api-provider-ibmcloud

Makefile
Resolve https://github.com/gyliu513/cluster-api-provider-ibmcloud/issues/1
- Add `depend` target in makefile
=> add depend target in makefile.

CONTRIBUTING.md
Fixes #
```release-note
NONE
```
/cc @bradtopol @jichenjc
=> Added contributing document.

cmd/clusterctl/definition/ibmcloud/clouds.yaml.template, cmd/clusterctl/definition/ibmcloud/cluster.yaml.template, cmd/clusterctl/definition/ibmcloud/machines.yaml.template
part of #21
Fixes #
```release-note
```
=> Add template for clouds, cluster, machine

cmd/clusterctl/example/ibmcloud/scripts/master-user-data.sh, cmd/clusterctl/example/ibmcloud/scripts/worker-user-data.sh
This is first step for #19
```release-note
```
=> scripts to deploy Kubernetes on IBM Cloud host 

pkg/cloud/ibmcloud/clients/machines.go
=> add guest list function

.travis.yml, hack/verify_docfiles.sh, scripts/build-images.sh, scripts/download-binaries.sh, scripts/pre-commit.sh
=> add travis.

pkg/apis/ibmcloud/v1alpha1/register.go
Fixes #14 
```release-note
```
=> Create function to convert spec/status from cluster-api

cmd/manager/main.go, pkg/cloud/ibmcloud/actuators/machine/actuator.go, pkg/cloud/ibmcloud/clients/machines.go, pkg/cloud/ibmcloud/types.go, pkg/controller/add_machine_controller.go, pkg/controller/controller.go
Add Exists function support 
Fixes #
```release-note
```
=> Add instance exist check

pkg/cloud/ibmcloud/actuators/machine/actuator.go
Get IP function implementation
Fixes #
```release-note
```
=> Add GetIP function

pkg/cloud/ibmcloud/actuators/machine/actuator.go
=> Add GetKubeConfig function

pkg/cloud/ibmcloud/actuators/machine/actuator.go, pkg/cloud/ibmcloud/clients/machines.go
=> Add instance delete function

cmd/clusterctl/example/ibmcloud/scripts/master-user-data.sh, cmd/clusterctl/example/ibmcloud/scripts/worker-user-data.sh, pkg/cloud/ibmcloud/actuators/machine/machine_script.go
=> add template parsing code for master and node scripts

cmd/clusterctl/.gitignore
=> Add ignore file for kubeconfig and clusterctl

pkg/apis/ibmcloud/v1alpha1/ibmcloudmachineproviderspec_types.go, pkg/apis/ibmcloud/v1alpha1/zz_generated.deepcopy.go, pkg/cloud/ibmcloud/actuators/machine/actuator.go, pkg/cloud/ibmcloud/clients/machines.go
=>  implement machine create implementation and rendering start up scripts

Makefile
=> build clusterctl

pkg/cloud/ibmcloud/actuators/machine/actuator.go
This is part of #43. 
`clusterctl` needs to get `IP` from annotation. So, the controller should annotate related information. ID is also updated for potential use.
=> annotate with ID and IP for created host

cmd/clusterctl/configuration/ibmcloud/provider-component/clouds-secrets/kustomization.yaml, cmd/clusterctl/configuration/ibmcloud/provider-component/cluster-api/kustomization.yaml, cmd/clusterctl/configuration/ibmcloud/provider-component/cluster-api/manager_image_patch.yaml, config/kustomization.yaml
Add kustomization file for subfolders
Fixes #
```release-note
```
=> Add kustomization file (part 1)

config/crds/ibmcloud_v1alpha1_ibmcloudmachineproviderspec.yaml
=> Add auto generated stuffs

config/manager/manager.yaml
1) namespace change
2) image change
Fixes #
```release-note
```
=> Add kustomize 2

pkg/bootstrap/token_test.go
Fixes #
```release-note
NONE
```
=> Added token test.

pkg/cloud/ibmcloud/actuators/machine/actuator.go
the boot token usage not added
Fixes #
```release-note
```
=> Follow up of bug/50

cmd/clusterctl/configuration/ibmcloud/scripts/launcher.sh, pkg/cloud/ibmcloud/clients/machines.go
It seems we will deploy a cluster soon (with bug fix of course because I did not test related part before)
=> deploy K8s when VM is started up

Makefile
=> add dep ensure into makefile

pkg/cloud/ibmcloud/clients/machines.go
It is a part of #57.
We still need to make cloud.yaml mount to controller pod.
=> get cloud.yaml authentication information from mounted file

cmd/clusterctl/configuration/ibmcloud/machines.yaml.template
this is requested by openstack related PR and should apply
to ibmcloud as well, see
https://github.com/kubernetes-sigs/cluster-api/blob/master/pkg/apis/cluster/v1alpha1/machine_types.go#L31
for additional info
Fixes #
```release-note
```
=> adds cluster.k8s.io/cluster-name into template

cmd/clusterctl/configuration/ibmcloud/generate-yaml.sh, cmd/clusterctl/configuration/ibmcloud/provider-component/clouds-secrets/configs/clouds.yaml, config/manager/manager.yaml
=> update generate yaml file

Gopkg.lock, Gopkg.toml, vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go, vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/clusterdeployer/clusterdeployer.go
Fixes #
```release-note
NONE
```
=> Switch to use cluster api release-0.1

Dockerfile, Makefile, cmd/clusterctl/configuration/ibmcloud/machines.yaml.template, cmd/manager/main.go, config/manager/manager.yaml, pkg/cloud/ibmcloud/actuators/cluster/actuator.go, pkg/cloud/ibmcloud/actuators/machine/actuator.go, pkg/cloud/ibmcloud/clients/machines.go
This will have several commits to make Machine `Create` path work for ibmcloud
=> make creation path work

cmd/clusterctl/configuration/ibmcloud/machines.yaml.template, cmd/clusterctl/configuration/ibmcloud/scripts/launcher.sh, pkg/apis/ibmcloud/v1alpha1/ibmcloudmachineproviderspec_types.go, pkg/cloud/ibmcloud/deployer.go
1. `sshUserName`
2. move `userData` script into `/` to avoid it is executed twice. I need this commit to continue the development.
=> specified ssh user and fix script run issue

pkg/cloud/ibmcloud/actuators/machine/actuator.go, pkg/cloud/ibmcloud/clients/machines.go
=> customized values of machine.yaml support

OWNERS, OWNERS_ALIASES, RELEASE.md, SECURITY_CONTACTS, code-of-conduct.md
Fixes #
```release-note
NONE
```
=> Added OWNERS.

OWNERS_ALIASES
Fixes #
```release-note
NONE
```
=> Correct OWNER files.

Makefile, config/default/manager_image_patch.yaml
Fixes #
```release-note
NONE
```
=> Added REGISTRY and VERSION for docker images.

pkg/cloud/ibmcloud/actuators/cluster/actuator.go, pkg/cloud/ibmcloud/actuators/machine/actuator.go, pkg/cloud/ibmcloud/clients/machines.go, pkg/cloud/ibmcloud/deployer.go
=> klog messages

README.md
Fixes #
```release-note
NONE
```
=> Used example instead of configuration in README.

pkg/cloud/ibmcloud/actuators/machine/actuator.go, pkg/cloud/ibmcloud/clients/machines.go
rename function 
and
fix log issues
=> function name should be verbe+none to tell the action

README.md
adjust image style in readme file.
Fixes #
```release-note
```
=> adjust image style in readme.

cmd/clusterctl/examples/ibmcloud/machines.yaml.template
Fixes #
```release-note
NONE
```
=> Deleted hostname from machines.yaml template.

cmd/clusterctl/examples/ibmcloud/machines.yaml.template
Fixes #
```release-note
NONE
```
=> Set default key name as cluster-api-provider-ibmcloud.

README.md
per #88, we can remove this line for now and add back later
when the clouds.yaml format changes.
Fixes #
```release-note
```
=> REmove yq usage in doc

pkg/cloud/ibmcloud/actuators/machine/actuator.go
1) a typo
2) the log is confusing for an error case
Fixes #
```release-note
```
=> Fix some nits

OWNERS, OWNERS_ALIASES
Fixes #
```release-note
NONE
```
Related to https://github.com/kubernetes/org/issues/782
=> Added sig-ibmcloud-admins group.

OWNERS, OWNERS_ALIASES
Fixes #
```release-note
NONE
```
=> Removed sig-ibmcloud-admins.

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
Fixes #
```release-note
NONE
```
/cc @xunpan @jichenjc
=> Added sig ibmcloud to issues and pr template.

Makefile, cmd/clusterctl/examples/ibmcloud/generate-yaml.sh
add generate yaml file test to avoid break code on the yaml file
Fixes #
/sig ibmcloud
```release-note
```
=> add generate yaml file test

cmd/clusterctl/examples/ibmcloud/generate-yaml.sh
forgot to remove it after debug...
Fixes #
/sig ibmcloud
```release-note
```
=> Fix a typo

README.md
Fixes #
/sig ibmcloud
```release-note
NONE
```
=> Added Go Report Card.

Makefile, config/manager/manager.yaml
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/113
/sig ibmcloud
```release-note
NONE
```
/cc @xunpan @jichenjc @hchenxa
=> Updated registry to quay.io/cluster-api-provider-ibmcloud.

OWNERS_ALIASES
Fixes #
/sig ibmcloud
```release-note
NONE
```
/cc @xunpan @jichenjc 
FYI @hchenxa
=> Added hchenxa as reviewer.

pkg/cloud/ibmcloud/clients/machines.go
add a timeout flag to avoid infinite wait
also, make it in const so we can use ENV later
Fixes #
/sig ibmcloud
```release-note
```
=> Timeout flag configuration enhancement

.github/PULL_REQUEST_TEMPLATE.md
Fixes #
/sig ibmcloud
```release-note
NONE
```
/cc @xunpan @jichenjc
=> Updated PR template by adding default reviewers.

pkg/cloud/ibmcloud/actuators/machine/actuator.go
=> add provider id

Makefile
Fixes kubebuilder dependency issue in prow jobs.
/sig ibmcloud
```release-note
```
=> fix kubebuilder issue.

Gopkg.lock, Gopkg.toml, vendor/k8s.io/klog/klog.go, vendor/k8s.io/klog/klog_file.go
It should be related to old version of klog.
upgrade to latest version can fix it.
Fixes #125
=> empty log message fix

examples/ubuntu/machines.yaml
Fixes #
@hemanthavs this `machines.yaml` can help for your test.
/sig ibmcloud
```release-note
NONE
```
=> Added ubuntu machine sample file.

Makefile
**Which issue(s) this PR fixes**:
Fixes make target `build-push-images` issue
/sig ibmcloud
```release-note
```
=> fix build-push-images target.

CONTRIBUTING.md
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/132
/sig ibmcloud
```release-note
```
=> update contributing doc.

README.md
Fixes #
/sig ibmcloud
```release-note
```
=> typo correct: IBM Cloud is the right name

config/default/manager_image_patch.yaml, config/manager/manager.yaml
let's use v0.0.1 as default by now
Fixes #
/sig ibmcloud
```release-note
```
=> the latest tag doesn't exist

pkg/cloud/ibmcloud/actuators/machine/actuator.go
to provide more info about machine liftcycle
Fixes #
/sig ibmcloud
```release-note
```
=> Add machine deleting status

config/manager/manager.yaml
from controller-manager to ibmcloud-machine-controller
Fixes #140 
/sig ibmcloud
```release-note
```
=> change name of manager statefulset

README.md
Fixes #143 
/sig ibmcloud
```release-note
```
=> Add doc about private key location

Makefile
it's removed previously but it should be kept because we need
it to auto generate crd for us in case any crd definition changed.
Fixes #
/sig ibmcloud
```release-note
```
=> Restore manifests build stage

pkg/cloud/ibmcloud/actuators/machine/actuator.go
This fix is related to #148
/sig ibmcloud
=> check guest if empty before use it.

cmd/manager/main.go, pkg/cloud/ibmcloud/actuators/machine/actuator.go, pkg/record/record.go
more events can be added later on
Part of #105 
/sig ibmcloud
```release-note
```
=> add event handling for create and delete

README.md, docs/ibmcloud_help.md
Fixes #
/sig ibmcloud
```release-note
```
=> os reference code document

docs/ibmcloud_help.md
Fixes #
/sig ibmcloud
```release-note
```
=> Add Datacenter into help info doc

pkg/cloud/ibmcloud/actuators/machine/actuator.go, pkg/cloud/ibmcloud/clients/machines.go
update. basic functions
**Which issue(s) this PR fixes** 
Related to  #16
/cc @gyliu513 @jichenjc
It is tested. However, I found an issue in `clusterctl` steps. I'd like to make sure if it is related to this issue.
/sig ibmcloud
=> update: when a machine specification changes, recreate the machine

Makefile, cmd/clusterctl/examples/ibmcloud/generate-yaml.sh, cmd/clusterctl/examples/ibmcloud/provider-component/clouds-secrets/kustomization.yaml, cmd/clusterctl/examples/ibmcloud/provider-component/cluster-api/kustomization.yaml, cmd/clusterctl/examples/ibmcloud/provider-component/user-data/ubuntu/kustomization.yaml
refer to
https://github.com/kubernetes-sigs/kustomize/commit/2fa4a3458924de6c3a1613fb0c69b2f658e6b3c7
we need modify the secret create process
Fixes:
/sig ibmcloud
```release-note
```
=> support latest kustomize

Makefile, README.md, cmd/clusterctl/examples/ibmcloud/generate-yaml.sh
kubectl has kustomize and we don't need download and use it.
Fixes #159 
/sig ibmcloud
```release-note
```
=> use kubectl for kustomize

CONTRIBUTING.md, RELEASE.md
run doctc under main folder found those 2 changes
Fixes #
/sig ibmcloud
```release-note
```
=> nit:Add doctc for some files

scripts/download-binaries.sh
upgrade kubectl because pre-commit.sh failed.
=> update download binaries to clean dependency for kustomize

README.md, docs/add_node.md
Fixes #
/sig ibmcloud
```release-note
```
=> Add guideline to add a new worker node

README.md
addons.yaml is from cluster-api, this adds some information
about how to use it and provide a simple sample.
Fixes #158 
/sig ibmcloud
```release-note
```
=> Add addons information

pkg/cloud/ibmcloud/actuators/machine/actuator.go, pkg/cloud/ibmcloud/deployer.go
=> remove uselsess id annotation, we have it in PROVIDERID

pkg/cloud/ibmcloud/clients/machines.go
=> get sshkey by filter instead of go though list

cmd/clusterctl/examples/ibmcloud/provider-component/user-data/ubuntu/templates/master-user-data.sh, cmd/clusterctl/examples/ibmcloud/provider-component/user-data/ubuntu/templates/worker-user-data.sh
the original code didn't handle the swap disable logic very
well and lead to /etc/fstab not updated
Fixes #181 
/sig ibmcloud
```release-note
```
=> disable swap permanently

cmd/clusterctl/examples/ibmcloud/generate-yaml.sh
below code will exited when the cluster.yaml exists.
```
mkdir -p $PWD/$OUTPUT
cp -n $PWD/cluster.yaml.template $PWD/$OUTPUT/cluster.yaml  >>>>>>>> The return code was 1
cp -n $PWD/machines.yaml.template $PWD/$OUTPUT/machines.yaml 
```
so in order to avoid the file overwrite and keep the updated file of cluster.yaml and machines.yaml, create this PR.
Fixes #
/cc @gyliu513 @clyang82 
/sig ibmcloud …
=> the generate.sh exited when the cluster.yaml exists

README.md, cmd/clusterctl/examples/ibmcloud/clouds.yaml.template, pkg/cloud/ibmcloud/clients/machines.go, pkg/cloud/types.go
Signed-off-by: clyang82 <clyang@cn.ibm.com>
This PR is for #62
=> format clouds.yaml for extension

README.md, cmd/clusterctl/examples/ibmcloud/machines.yaml.template
Signed-off-by: Chun Lin Yang <clyang@cn.ibm.com>
This PR is for #192 
/assign @gyliu513 @xunpan @jichenjc
=> Add explaination for sshUserName

README.md, cmd/clusterctl/examples/ibmcloud/cluster.yaml.template, docs/trouble_shooting.md, pkg/cloud/ibmcloud/clients/machines.go
Fixes #153 
/sig ibmcloud
```release-note
```
=> fix pod and node ip override issue.

.travis.yml, Makefile, config/manager/manager.yaml
This PR is used to enable travis to generate daily image for `manager` and `clusterctl` from master. refer to #202 
Signed-off-by: Chun Lin Yang <clyang@cn.ibm.com>
=> Add travis for building

cmd/clusterctl/Dockerfile
This PR is for #210 
Signed-off-by: Chun Lin Yang <clyang@cn.ibm.com>
=> Fix VA issues for clusterctl

README.md, cmd/clusterctl/examples/ibmcloud/machines.yaml.template, docs/ibmcloud_help.md
Correct commands of readme 
Fixes #197 
/sig ibmcloud
No changes on image
None
=> Remind user to check yaml file before creating a cluster

hack/verify-golint.sh
This is related to https://github.com/kubeflow/kfserving/issues/135
Fixes #
/sig ibmcloud
```release-note
NONE
```
=> Fixed golint issue.

pkg/cloud/ibmcloud/deployer.go
this return IP will be a periodic task and no need to be
showing during normal case (without debug)
Fixes #
/sig ibmcloud
```release-note
```
=> move log info to v3 level

pkg/cloud/ibmcloud/deployer.go
A consistent format with `=` in `-o` options make better debug message in readability and easy for checking command manually.
This is related to #216
/sig ibmcloud
```release-note
```
=> make command line format consistent for better debug message display

cmd/clusterctl/Dockerfile
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/222
/cc @gyliu513 @jichenjc @xunpan @hchenxa 
/sig ibmcloud
```release-note
```
=> Adding KIND to clusterctl docker image

config/rbac/rbac_role.yaml, pkg/cloud/ibmcloud/actuators/machine/actuator.go
Fixes #200 
/sig ibmcloud
```release-note
```
=> Add nod ref

pkg/cloud/ibmcloud/actuators/machine/actuator.go
Seems incorrect word
/sig ibmcloud
No image version change
```release-note
NONE
```
=> correct word

README.md, docs/how_to_use_clusterctl.md, examples/clusterctl/clusterrole.yaml, examples/clusterctl/clusterrolebinding.yaml, examples/clusterctl/job.yaml, examples/clusterctl/serviceaccount.yaml
Signed-off-by: Chun Lin Yang <clyang@cn.ibm.com>
**Which issue(s) this PR fixes** 
Fixes #226 
/cc @gyliu513 @jichenjc @xunpan @hchenxa 
/sig ibmcloud
=> README: How to use clusterctl

README.md
Fix typo and add some cases for readability
/sig ibmcloud
No image version change
```release-note
NONE
```
=> Fix typo and add some cases for readability

CONTRIBUTING.md
Fixes #
/sig ibmcloud
```release-note
NONE
```
=> Added a new section for how to request member.

cmd/clusterctl/examples/ibmcloud/machines.yaml.template, config/crds/ibmcloud_v1alpha1_ibmcloudmachineproviderspec.yaml, docs/add_node.md, docs/ibmcloud_help.md, pkg/apis/ibmcloud/v1alpha1/ibmcloudmachineproviderspec_types.go, pkg/cloud/ibmcloud/actuators/machine/actuator.go, pkg/cloud/ibmcloud/clients/machines.go
we should use flavor instead of asking end user to specify the
memory, cpu etc value.
Fixes #164 
/sig ibmcloud
```release-note
```
=> Add flavor support

examples/ubuntu/machines.yaml
Fixes #
/sig ibmcloud
```release-note
NONE
```
=> Updated ubuntu example to use flavor.

Gopkg.lock, Gopkg.toml, vendor/github.com/softlayer/softlayer-go/datatypes/account.go, vendor/github.com/softlayer/softlayer-go/datatypes/container.go, vendor/github.com/softlayer/softlayer-go/datatypes/exception.go, vendor/github.com/softlayer/softlayer-go/datatypes/hardware.go, vendor/github.com/softlayer/softlayer-go/datatypes/metric.go, vendor/github.com/softlayer/softlayer-go/datatypes/network.go, vendor/github.com/softlayer/softlayer-go/datatypes/security.go, vendor/github.com/softlayer/softlayer-go/datatypes/ticket.go, vendor/github.com/softlayer/softlayer-go/datatypes/user.go, vendor/github.com/softlayer/softlayer-go/services/account.go, vendor/github.com/softlayer/softlayer-go/services/brand.go, vendor/github.com/softlayer/softlayer-go/services/hardware.go, vendor/github.com/softlayer/softlayer-go/services/network.go, vendor/github.com/softlayer/softlayer-go/services/security.go, vendor/github.com/softlayer/softlayer-go/services/ticket.go, vendor/github.com/softlayer/softlayer-go/services/user.go, vendor/github.com/softlayer/softlayer-go/services/virtual.go
also, updated to latest commit as some API already not supported
we should not use old stuff
see https://github.com/softlayer/softlayer-go/commit/ba6e7f29521771a05a8faa6c1782735b4b74dc36
for more info
Fixes #247 
/sig ibmcloud
```release-note
```
=> fix warning '7c592eb' should not be abbreviated form

docs/ibmcloud_help.md, docs/trouble_shooting.md
Fixes #
/sig ibmcloud
```release-note
```
=> Fix docs to add some lines

README.md
Add a tips for use kind to create a cluster
Fixed https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/227
/sig ibmcloud
No image version change
```release-note
NONE
```
=> Add a tips for use kind to create a cluster

docs/ibmcloud_help.md, docs/trouble_shooting.md
Fixes #
/sig ibmcloud
```release-note
```
=> Update words of trouble shooting

README.md
Fixes #
/sig ibmcloud
```release-note
NONE
```
=> Correct the link for install kubectl.

cmd/clusterctl/examples/ibmcloud/provider-component/user-data/ubuntu/templates/master-user-data.sh, cmd/clusterctl/examples/ibmcloud/provider-component/user-data/ubuntu/templates/worker-user-data.sh, docs/taint_node.md, pkg/cloud/ibmcloud/actuators/machine/machine_script.go
Fixes #240 
/sig ibmcloud
```release-note
```
=> add taint support to master and worker node

cmd/clusterctl/examples/ibmcloud/machines.yaml.template
able to create like
NAME                  STATUS   ROLES    AGE     VERSION
jichen-master-9hbpr   Ready    master   7m57s   v1.15.0
jichen-node-whblt     Ready    <none>   2m20s   v1.15.0
Fixes #
/sig ibmcloud
```release-note
```
=> update version 1.14 to 1.15

pkg/cloud/ibmcloud/actuators/machine/actuator.go
the current log looks bad such as
actuator.go:296] Setting machine's nodeRef machine-namejichen-node-8qjjmdefaultjichen-node-8qjjm
Fixes #
/sig ibmcloud
```release-note
```
=> enhance log for set node ref

pkg/cloud/ibmcloud/actuators/machine/actuator.go
Error message
Fixes #
/sig ibmcloud
```release-note
NONE
```
=> Update error message

pkg/cloud/ibmcloud/actuators/machine/actuator.go
update keep saying can't find all param but actually
it's not returned the ibmcloud side
Fixes #
/sig ibmcloud
```release-note
```
=> Add more log to help debug update issue

pkg/cloud/ibmcloud/actuators/cluster/actuator.go, pkg/cloud/ibmcloud/actuators/cluster/actuator_test.go
add unit test and remove duplicate comment.
Test passed and the error message shows from line 75 of actuator.go because of use fake client in test code.
```
ok      sigs.k8s.io/cluster-api-provider-ibmcloud/pkg/cloud/ibmcloud    (cached)
=== RUN   TestDelete
--- PASS: TestDelete (0.00s)
=== RUN   TestReconcile
E0728 22:02:39.391197    2525 actuator.go:61] failed to store provider status for cluster "testCluster" in namespace "testNamespace": failed to update cluster status for cluster "testCluster" in namespace "testNamespace": no kind is registered for the type v1alpha1.Cluster in scheme "k8s.io/client-go/kubernetes/scheme/register.go:61"
--- PASS: TestReconcile (0.00s)
PASS
ok      sigs.k8s.io/cluster-api-provider-ibmcloud/pkg/cloud/ibmcloud/actuat …
```
=> Add unit test and remove duplicated comment

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/269
/cc @spzala @jichenjc @xunpan
/sig ibmcloud
```release-note
NONE
```
=> Change label to area/provider/ibmcloud

OWNERS, OWNERS_ALIASES, README.md
Changes related to sig ibm cloud became provider ibm cloud. 
Fixes # 269
```release-note
```
=> Changes related to sig ibm cloud rename

Gopkg.lock, vendor/github.com/evanphx/json-patch/LICENSE, vendor/github.com/evanphx/json-patch/errors.go, vendor/github.com/evanphx/json-patch/merge.go, vendor/github.com/evanphx/json-patch/patch.go, vendor/k8s.io/client-go/testing/actions.go, vendor/k8s.io/client-go/testing/fake.go, vendor/k8s.io/client-go/testing/fixture.go, vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go, vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
Fixes #
```release-note
NONE
```
=> dep ensure to sync up code.

pkg/apis/ibmcloud/v1alpha1/ibmcloudmachineproviderspec_types.go, pkg/cloud/ibmcloud/clients/machines.go, pkg/cloud/ibmcloud/deployer.go, pkg/cloud/ibmcloud/deployer_test.go
* Fix golint error and normalize variable or function naming
=> Normalize variable and function naming

.travis.yml
Fixes #
```release-note
NONE
```
=> Enabled multi-arch image build.

cmd/manager/main.go
Fixes #279 
```release-note
```
=> unique leader election id

.gitignore, cmd/clusterctl/examples/ibmcloud/generate-yaml.sh
Fixes #286 
```release-note
```
=> fix issue #286

config/rbac/auth_proxy_service.yaml, config/rbac/role.yaml
Fix deployment issue when make deploy and the rbac issue after deploying
Fixes #312
/cc @gyliu513 @jichenjc @xunpan @wentao-zh
```release-note
```
=> #312: Fix deploy issue

OWNERS_ALIASES
=> Adding mkumatag  to OWNERS

cloudbuild.yaml
This PR is for creating the cloudbuild.yaml which contains the definition of how to build the image for this repo.
More information: https://github.com/kubernetes/test-infra/blob/c5f5b3155733140e6cbd83185862df85935c0f1c/config/jobs/image-pushing/README.md
Fixes #
Ref: https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/332 …
=> Add cloudbuild.yaml file

controllers/ibmpowervscluster_controller_test.go, controllers/ibmpowervsmachine_controller_test.go
This PR adds unit tests for PowerVS
Fixes #
/cc @gyliu513 @jichenjc @xunpan @mkumatag 
```release-note
NONE
```
=> Adding unit tests- powervs

.gitignore, tilt-provider.json
Instructions how to use tilt - https://cluster-api.sigs.k8s.io/developer/tilt.html
tilt-settings.json
```json
{
"default_registry": "localhost:5000",
"provider_repos": ["../cluster-api-provider-ibmcloud"],
"enable_providers": ["ibmcloud", "kubeadm-bootstrap", "kubeadm-control-plane"],
"kustomize_substitutions": {
"IBMCLOUD_API_KEY":"<Replace with proper api key>"
}
}
```
Fixes #361
```release-note
```
=> tilt configuration

api/v1alpha3/ibmvpccluster_types.go, api/v1alpha3/types.go, api/v1alpha4/ibmpowervsmachinetemplate_types.go, api/v1alpha4/ibmvpccluster_types.go, api/v1alpha4/types.go, cloud/scope/clients.go, cloud/scope/cluster.go, cloud/scope/machine.go, cloud/scope/powervs_cluster.go, cloud/scope/powervs_machine.go, config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachinetemplates.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcclusters.yaml, controllers/ibmpowervscluster_controller.go, controllers/ibmpowervsmachine_controller.go, controllers/ibmvpccluster_controller.go, controllers/ibmvpcmachine_controller.go, pkg/client.go
This PR contain the changes to improve linting
Fixes #338
```release-note
```
=> Fix for golint issues

cloud/scope/cluster.go, cloud/scope/machine.go, cloud/scope/powervs_clients.go
This PR helps in improving the code linting
Fixes #418
```release-note
```
=> Improve golint

OWNERS
=> Added wentao-zh and relyt0925 as reviewer

README.md, docs/book/src/topics/powervs/creating-a-cluster.md, docs/book/src/topics/powervs/prerequisites.md, templates/README.md
1. Update readme docs
2. Add PowerVS specific cluster deployment doc
Fixes #432 
```release-note
```
=> Update Readme docs

main.go
Fixes #451 
```release-note
```
=> Watch Namespace

cloud/scope/powervs_clients.go, cloud/scope/powervs_machine.go, controllers/ibmpowervsmachine_controller.go, go.mod, go.sum
This PR adds changes for updating power-go-client to 1.0.79 or later versions.
Fixes #448 
```release-note
NONE
```
=> Updating power-go-client to 1.0.80

cloud/scope/cluster.go, cloud/scope/machine.go, controllers/ibmvpccluster_controller.go, controllers/ibmvpcmachine_controller.go
The controller wasn't using a proper API version and still was referring the older version, the `release-0.1` need this fix to work properly with `v1alpha4` version
Fixes #
```release-note
```
=> Use proper api version

docs/book/src/SUMMARY.md, docs/book/src/developer/conversion.md, docs/book/src/developer/index.md
1. Add initial draft doc supporting v1alpha4 -> v1betav1 conversion process
Fixes #
```release-note
```
=> Add conversion doc

go.mod, go.sum, main.go
Fixes #457 
```release-note
```
=> Use klogr for logging

cloud/scope/powervs_clients.go, cloud/scope/powervs_machine.go, go.mod, go.sum
Updates the power-go-client module to 1.0.85
Fixes #484 
```release-note
NONE
```
=> Updating power-go-client to 1.0.85

config/manager/manager.yaml, main.go
Fixes #463 
```release-note
```
=> support for healthz

Makefile, test/e2e/config/ibmcloud-e2e-powervs.yaml, test/e2e/config/ibmcloud-e2e-vpc.yaml, test/e2e/e2e_test.go, test/e2e/suite_test.go
This PR adds e2e test cases
Fixes #433 
```release-note
NONE
```
=> Adding e2e test cases

docs/book/src/developer/tilt.md
This doc will help the developers to add extra_args to the tilt settings to generate requests/responses.
Fixes #
```release-note
```
=> Doc to log requests/responses for powervs apis

OWNERS
This PR https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/516 removed @spzala by mistake, we need to add him back.
@mkumatag @spzala 
Fixes #
```release-note
```
=> Added spzala back to reviewers

cloud/scope/powervs_cluster.go, cloud/scope/powervs_machine.go
Fixes #521 
```release-note
```
=> Handle scope creation properly

.gitignore, scripts/ci-e2e.sh
Adds script used for E2E prow job.
Fixes #433
```release-note
NONE
```
=> Add e2e-test script

controllers/ibmpowervscluster_controller.go, controllers/ibmpowervsimage_controller.go
Fix IBMPowerVSImage deletion
- Delete IBMPowerVSImage on deletion of IBMPowerVSCluster
Fixes #538 
```release-note
```
=> Fix IBMPowerVSImage deletion

cloud/scope/powervs_machine.go, controllers/ibmpowervsmachine_controller.go
Fixes #561 
```release-note
```
=> Adding more addresses to the machine spec

api/v1beta1/ibmpowervsmachine_types.go, api/v1beta1/zz_generated.deepcopy.go
Fixes #573 
```release-note
```
=> Use LocalObjectReference for ImageRef

Dockerfile
Latest Golang version is available, hence needs to be updated in the docker file
Fixes #
```release-note
```
=> update golang version in the dockerfile

cloud/scope/powervs_test.go, cloud/scope/suite_test.go
This PRs adds unit tests for PowerVS machine creation. 
Fixes #
```release-note
NONE
```
=> Add unit tests for PowerVS

cloud/scope/powervs_test.go
This PR adds unit tests cases for Powervs image.
Fixes #581 
```release-note
```
=> Add unit tests for Powervs image handling

cloud/scope/powervs_machine.go
Fixes #583 
```release-note
```
=> trim whitespace from the ip address

docs/book/src/SUMMARY.md, docs/book/src/machine-images/index.md, docs/book/src/machine-images/powervs.md, docs/book/src/machine-images/vpc.md
Publish the documentation for the images used for the deployment
Fixes #
```release-note
```
=> Add doc for the images

cloud/scope/powervs_image.go
- PowerVSImageScope set debug true only if log level set 5 and above
Fixes #597 
```release-note
```
=> PowerVSImageScope set debug true only if log level set 5 and above

Makefile, hack/tools/Makefile
- fix make verify-conversions check
Fixes #585 
```release-note
```
=> fix make verify-conversions check

cloud/scope/cluster.go, cloud/scope/machine.go, config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsimages.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachinetemplates.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcmachinetemplates.yaml, controllers/ibmvpccluster_controller.go, controllers/ibmvpcmachine_controller.go, docs/book/src/getting-started.md
- Fix VPC related issues
- Fix service endpoint url
- Add proper resource group ID to function calls
- Minor post-liniting process updates
Fixes #615 
```release-note
Fix VPC related issues and minor lint updates.
```
=> Fix VPC related issues and minor lint updates

docs/book/src/machine-images/powervs.md
Fixes #591
```release-note
```
=> Add k8s 1.23.5 image

templates/cluster-template-powervs-cloud-provider.yaml
This PR will update the IBM Power VS cloud controller image name
Fixes #
```release-note
NONE
```
=> Update powervs cloud controller image name

docs/book/src/machine-images/powervs.md
=> Fix URL typo for PowerVS image

cloud/scope/powervs_image.go
- Refine the events
Fixes #637 
```release-note
Refine the events
```
=> Refine the events

Dockerfile
Update the golang version in the Dockerfile
Fixes #
```release-note
```
=> update golang version

templates/cluster-template-powervs-cloud-provider.yaml, templates/cluster-template-powervs.yaml
Used the doc here - https://kube-vip.chipzoller.dev/docs/installation/static/#generating-a-manifest to generate the manifest and updated it accordingly.
Fixes #628 
```release-note
```
=> Update the kube-vip to v0.4.4

docs/book/src/getting-started.md
Enhancing the getting started doc to add debug log level information.
Fixes #644 
```release-note
NONE
```
=> Update doc for enabling debug logs 

cloud/scope/cluster.go, cloud/scope/machine.go
- Enable debug logs for vpc
- Expose additional spec params
Fixes #625 
```release-note
enable debug logs for vpc and expose additional spec params
```
=> enable debug logs for vpc

api/v1beta1/common.go, api/v1beta1/common_test.go, api/v1beta1/ibmpowervsmachine_types.go, api/v1beta1/ibmpowervsmachine_webhook.go, api/v1beta1/ibmpowervsmachinetemplate_webhook.go, config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachinetemplates.yaml
- Validate machine spec memory/processors values.
Fixes #596 
```release-note
Validate machine spec values.
```
=> Validate machine spec values

README.md
**What this PR does / why we need it**: 
Fixes #657 
```release-note
```
=> Fix version image shield

OWNERS
Prajyot-Parab is active contributor to this project and well verse with the entire code, hence adding him as a reviewer.
Fixes #
```release-note
```
=> Add Prajyot-Parab as reviewer

cloud/scope/powervs_machine.go, controllers/ibmpowervsmachine_controller.go
This PR allows to report controller errors to the machine status, later this can be used by the `MachineHealthCheck`
Fixes #645 
```release-note
```
=> Register the errors for the powervs vm build failure

docs/book/src/topics/powervs/creating-a-cluster.md, templates/README.md, templates/cluster-template-powervs-cloud-provider.yaml, templates/cluster-template-powervs.yaml
- Expose additional spec params
Fixes #
```release-note
Expose additional spec params
```
=> Expose additional spec params

Makefile, hack/tools/Makefile
- Refactor and update Makefile
Fixes #607 
```release-note
Refactor and update Makefile
```
=> Refactor and update Makefiles

cloud/scope/cluster.go, cloud/scope/machine.go, cloud/scope/powervs_cluster.go, cloud/scope/powervs_image.go, cloud/scope/powervs_machine.go, config/default/credentials.yaml, config/manager/manager.yaml, controllers/ibmpowervscluster_controller.go, controllers/ibmpowervsimage_controller.go, controllers/ibmpowervsmachine_controller.go, controllers/ibmvpccluster_controller.go, controllers/ibmvpcmachine_controller.go, docs/book/src/developer/tilt.md, docs/book/src/getting-started.md, go.mod, go.sum, main.go, pkg/cloud/services/resourcecontroller/resourcecontroller.go, pkg/cloud/services/resourcecontroller/service.go, pkg/endpoints/doc.go, pkg/endpoints/endpoints.go, pkg/endpoints/endpoints_test.go, test/e2e/config/ibmcloud-e2e-powervs.yaml, test/e2e/config/ibmcloud-e2e-vpc.yaml
- Support custom service endpoints
Fixes #592 
```release-note
Support custom service endpoints
```
=> Support PowerVS custom service endpoints

Dockerfile, hack/ccm/Dockerfile
Update the golang to latest available version
Fixes #
```release-note
```
=> Update golang version to 1.17.11

docs/book/src/machine-images/powervs.md
Fixes #708 
```release-note
```
=> Add powervs image for k8s 1.24.2

go.mod, go.sum
- Bump powervs-utils version
Fixes #
```release-note
Bump powervs-utils version
```
=> Bump powervs-utils version

Dockerfile, hack/ccm/Dockerfile
Fixes #666 
```release-note
```
=> Update docker to 1.18 version

controllers/ibmvpcmachine_controller.go, go.mod, go.sum
Fixes #731 
```release-note
```
=> Update vpc-go-sdk to v0.20.0

controllers/ibmvpcmachine_controller.go, go.mod, go.sum
Fixes #371 
```release-note
```
=> Update vpc sdk

Makefile, hack/tools/Makefile
Adds support to generate junit xml for better reporting on unit tests.
Fixes #707 
```release-note
```
=> Generate junit xml report for unit tests

cloud/scope/cluster_test.go, cloud/scope/common_test.go, cloud/scope/machine_test.go, cloud/scope/powervs_cluster_test.go, cloud/scope/powervs_image.go, cloud/scope/powervs_image_test.go, cloud/scope/powervs_machine.go, cloud/scope/powervs_machine_test.go, cloud/scope/suite_test.go
- Improve UT coverage in cloud/scope package for PowerVS
Fixes #
```release-note
Improve UT coverage in cloud/scope package for PowerVS
```
=> Improve UT coverage in cloud/scope package for PowerVS

Makefile, config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsimages.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachinetemplates.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcmachinetemplates.yaml
- Update config files
Fixes #
```release-note
Update config files
```
=> Add verify-manifests target and fix config files

cloud/scope/powervs_machine.go, controllers/ibmpowervsmachine_controller.go, pkg/cloud/services/powervs/caching.go, pkg/cloud/services/powervs/mock/powervs_generated.go, pkg/cloud/services/powervs/powervs.go, pkg/cloud/services/powervs/service.go
Fetch the Internal IP from the DHCP server 
Fixes #
```release-note
```
=> Fetch internal IP from dhcp server

docs/book/src/topics/powervs/creating-a-cluster.md, docs/book/src/topics/vpc/creating-a-cluster.md
- Update cluster creation flow in doc
- CNI deployment to be done on workload cluster for nodes to become Ready. (Current flow deploys CNI on management cluster, which does not update state of workload cluster nodes to Ready)
Fixes #
```release-note
Update cluster creation flow in doc
```
=> Update cluster creation flow in doc

cloud/scope/powervs_cluster.go, cloud/scope/powervs_image.go, cloud/scope/powervs_machine.go, go.mod, go.sum, pkg/endpoints/endpoints.go, pkg/endpoints/endpoints_test.go
- Remove powervs-utils package dependency
Fixes #643 
```release-note
Remove powervs-utils package dependency
```
=> Remove powervs-utils package dependency

cloud/scope/powervs_image.go
- Minor IBMPowerVSImage bugfix
Fixes #
```release-note
Minor IBMPowerVSImage bugfix
```
=> Minor IBMPowerVSImage bugfix

Dockerfile, hack/ccm/Dockerfile
This changes the golang version in the docker file to 1.18.4 version
Fixes #
```release-note
```
=> Update golang to 1.18.4

cloud/scope/cluster_test.go, cloud/scope/machine_test.go, cloud/scope/powervs_image_test.go, cloud/scope/powervs_machine_test.go, controllers/ibmpowervsimage_controller_test.go, controllers/ibmpowervsmachine_controller_test.go, controllers/ibmvpccluster_controller_test.go, controllers/ibmvpcmachine_controller_test.go
- Refactors the UT structure 
- Fixes mock PowerVS client calls
Fixes #
```release-note
```
=> Fix mock client calls in unit tests

controllers/ibmpowervscluster_controller_test.go
Adds test cases for IBMPowerVSCluster reconcile delete operations.
Fixes #
```release-note
```
=> Improve UT coverage for IBMPowerVSCluster controller

docs/book/src/topics/vpc/creating-a-cluster.md
- Refactor and add VPC variable references
Fixes #572 
```release-note
Refactor and add VPC variable references
```
=> Refactor and add VPC variable references

config/default/manager_auth_proxy_patch.yaml
-  Bump gcr.io/kubebuilder/kube-rbac-proxy to v0.13.0
Fixes #783 
```release-note
Bump gcr.io/kubebuilder/kube-rbac-proxy to v0.13.0
```
=> Bump gcr.io/kubebuilder/kube-rbac-proxy to v0.13.0

config/default/manager_auth_proxy_patch.yaml
- Bump gcr.io/kubebuilder/kube-rbac-proxy to v0.12.0
Fixes #
```release-note
Bump gcr.io/kubebuilder/kube-rbac-proxy to v0.12.0
```
=> Bump gcr.io/kubebuilder/kube-rbac-proxy to v0.12.0

api/v1beta1/ibmpowervscluster_webhook_test.go, api/v1beta1/ibmpowervsmachine_webhook_test.go, api/v1beta1/ibmpowervsmachinetemplate_webhook_test.go, api/v1beta1/ibmvpcmachine_webhook_test.go, api/v1beta1/ibmvpcmachinetemplate_webhook_test.go, api/v1beta1/suite_test.go
Adds UT for webhooks
Fixes #
```release-note
```
=> Add unit tests for webhooks

Dockerfile, hack/ccm/Dockerfile
Fixes #791 
```release-note
```
=> Update the golang version to 1.18.5

Makefile, hack/tools/Makefile, scripts/ci-apidiff.sh
- Add apidiff target to Makefile for checking API compatibility between different revisions.
Fixes #789 
```release-note
Add apidiff target
```
=> Add apidiff target

test/e2e/config/ibmcloud-e2e-powervs.yaml, test/e2e/data/templates/cluster-template-md-remediation.yaml
- Integrate MHC for worker nodes with e2e flow
Fixes #
```release-note
Integrate MHC for worker nodes with e2e flow
```
=> Integrate MHC for worker nodes with e2e flow

hack/boskos.sh, scripts/ci-e2e.sh
This PR adds changes to use Boskos resources of type powervs-service instead of using network resource type.
Fixes #623 
```release-note
Enhance E2E job to use powervs-service resources
```
=> Enhance E2E job

go.mod, go.sum, hack/tools/go.mod
- Update the version with proper version
- Positioned the replace statement for the cluster-api in the beginning to avoid unnoticed.
- Remove capi replace statement which aren't required.
Fixes #
```release-note
```
=> Update the go mods

tilt-provider.json
Fixes #https://github.com/kubernetes-sigs/cluster-api/issues/7201
```release-note
```
=> Move label field under config to fix tilt up error

cloud/scope/machine.go, controllers/ibmpowervsmachine_controller.go, controllers/ibmvpcmachine_controller.go
The removed log messages weren't much useful but increases the logfile size, hence removed them.
Fixes #
```release-note
```
=> Remove unwanted logs

docs/book/src/SUMMARY.md, docs/book/src/topics/vpc/load-balancer.md, templates/cluster-template-load-balancer.yaml
- Add VPC Load Balancer template
Fixes #835 
```release-note
Add VPC Load Balancer template
```
=> Add VPC Load Balancer template

go.mod, go.sum, hack/tools/go.mod, hack/tools/go.sum, test/e2e/config/ibmcloud-e2e-powervs.yaml, test/e2e/config/ibmcloud-e2e-vpc.yaml
Update cluster-api to v1.2.2
Fixes #866 
```release-note
Bump cluster-api to v1.2.2
```
=> Update cluster-api to v1.2.2

hack/ccm/Makefile, templates/cluster-template-powervs-cloud-provider.yaml
This PR contains the changes to use the latest cloud-provider-powervs changes
Update the ccm daemon set node selector and toleration.
Fixes #
```release-note
```
=> Update node selector and toleration for ccm

cloud/scope/machine.go, cloud/scope/machine_test.go
- Fix reconcileDelete machine flow for vpc
Fixes #849 
```release-note
Fix reconcileDelete machine flow for vpc
```
=> Fix reconcileDelete machine flow for VPC

hack/ensure-go.sh
=> Fix go version in the hack/ensure-go.sh script

Dockerfile, hack/ccm/Dockerfile
=> Bump golang to 1.18.6

docs/book/src/reference/regions-zones-mapping.md
=> Improve information for the Region/Zone mapping doc

scripts/ci-e2e.sh
Fixes #893 
```release-note
```
=> Fix the ibmcloud cli panic

main.go
Moved similar code blocks under a function for better structuring
Fixes #
```release-note
```
=> Organise code blocks in main.go file

docs/book/src/machine-images/vpc.md
- Publish VPC image for k8s 1.25.2 version
Fixes #
```release-note
Publish VPC image for k8s 1.25.2 version
```
=> Publish VPC image for k8s 1.25.2 version

cloud/scope/powervs_cluster.go, cloud/scope/powervs_image.go, cloud/scope/powervs_machine.go, controllers/ibmpowervscluster_controller.go, controllers/ibmpowervscluster_controller_test.go, controllers/ibmpowervsimage_controller.go, controllers/ibmpowervsimage_controller_test.go, controllers/ibmpowervsmachine_controller.go, controllers/ibmpowervsmachinetemplate_controller.go, controllers/ibmpowervsmachinetemplate_controller_test.go, main.go
This PR is an attempt to update usage of log and standardize log messages as per capi standards for all Power VS related controllers: https://cluster-api.sigs.k8s.io/developer/logging.html
Fixes #
```release-note
```
=> Update logs as per capi standards

go.mod, go.sum, hack/tools/go.mod, hack/tools/go.sum, test/e2e/config/ibmcloud-e2e-powervs.yaml, test/e2e/config/ibmcloud-e2e-vpc.yaml
- Update cluster-api to v1.2.3
Fixes #911 
```release-note
Update cluster-api to v1.2.3
```
=> Update cluster-api to v1.2.3

go.mod, go.sum, test/e2e/config/ibmcloud-e2e-powervs.yaml, test/e2e/config/ibmcloud-e2e-vpc.yaml
- Update cluster-api to v1.2.4
Fixes #
```release-note
Update cluster-api to v1.2.4
```
=> Update cluster-api to v1.2.4

.golangci.yml
- Improve gocyclo score within recommended range (10-20)
Fixes #927 
```release-note
Improve gocyclo score within recommended range
```
=> Improve gocyclo score within recommended range

.gitignore, scripts/ci-e2e.sh
Currently, in e2e tests, the latest version of IBM Cloud CLI is being downloaded. This PR adds support to use a specific stable version of the CLI.
Fixes #929 
```release-note
```
=> Use a fixed version of IBM Cloud CLI for e2e tests

scripts/ci-e2e.sh
IBM Cloud CLI installation fails on Linux platforms due to a minor typo issue in the name of the binary file.
Fixes #
```release-note
```
=> Fix minor issue with installing ibmcloud cli

go.mod, go.sum, hack/tools/go.mod, hack/tools/go.sum, test/e2e/config/ibmcloud-e2e-powervs.yaml, test/e2e/config/ibmcloud-e2e-vpc.yaml
- Update cluster-api to v1.2.5 (#953)
Fixes #951 
```release-note
Update cluster-api to v1.2.5 (#953)
```
=> [release-0.3] Update cluster-api to v1.2.5 (#953)

metadata.yaml, test/e2e/config/ibmcloud-e2e-powervs.yaml, test/e2e/config/ibmcloud-e2e-vpc.yaml
Updates release version to v0.4 in `metadata.yaml` and test config file
Fixes #
```release-note
```
=> Update release version in metadata.yaml and test config file

docs/book/src/SUMMARY.md, docs/book/src/developer/dependencies.md
Adds information about the versions being used by a few important modules and tools.
Fixes #930 
```release-note
```
=> Add doc for dependecy version mapping

go.mod, go.sum, hack/tools/go.mod, hack/tools/go.sum, test/e2e/config/ibmcloud-e2e-powervs.yaml, test/e2e/config/ibmcloud-e2e-vpc.yaml
- Updates cluster-api to `v1.3.0`
- Updates ginkgo to `v2.5.1` in `hack/tools/go.mod`
Fixes #981
```release-note
Update cluster-api to v1.3.0
```
=> Update cluster-api and ginkgo

docs/book/src/SUMMARY.md, docs/book/src/reference/api-references.md
This PR adds the API references to the References section pointing to CRD and godoc sites for the developers
Fixes #
```release-note
```
=> Add API References

docs/proposal/20230113-capibm-cli-tool.md
This PR contains the proposal for capiibm cli tool, mainly focusing on the various commands we can think of as need and the tool directory structures.
Few command arguments are not fully mentioned instead referred to existing commands in tools like ibmcloud or pvsadm cli. Idea is to update this document with actual list of argument during the course of development or once completed.
Fixes #
```release-note
```
=> Proposal for capibmadm cli tool

Dockerfile, hack/ccm/Dockerfile
=> Update golang to 1.19.5

api/v1beta2/ibmpowervsmachine_types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachinetemplates.yaml
- Minor spec comments update
Fixes #
```release-note
Minor spec comments update
```
=> Minor spec comments update

Dockerfile, api/v1beta1/suite_test.go, cloud/scope/suite_test.go, hack/ccm/Dockerfile
- Update golang to 1.18.10 version includes security fixes.
- Update small formatting in the code
Fixes #
```release-note
```
=> Update golang to 1.18.10

scripts/ci-e2e.sh, test/e2e/config/ibmcloud-e2e-powervs.yaml
Updates K8s version for e2e and uses new image.
Fixes #
```release-note
```
=> Update Kubernetes version for PowerVS e2e

scripts/ci-e2e.sh, test/e2e/config/ibmcloud-e2e-vpc.yaml, test/e2e/data/cni/calico/calico.yaml
- Minor e2e related fixes
- PodDisruptionBudget `policy/v1beta1` is now deprecated
Fixes #
```release-note
Minor e2e related fixes
```
=> Minor e2e related fixes

cloud/scope/cluster.go, cloud/scope/machine.go, pkg/cloud/services/utils/paging.go
- Implement paging mechaism
Fixes #1034
```release-note
Implement paging mechaism
```
=> Implement paging mechaism

docs/book/src/topics/vpc/load-balancer.md
=> Fix environment variable IBMCLOUD_API_KEY assigment

README.md
- update compatibility matrix
Fixes #
```release-note
update compatibility matrix
```
=> update compatibility matrix

go.mod, go.sum, hack/tools/go.mod, hack/tools/go.sum, test/e2e/config/ibmcloud-e2e-powervs.yaml, test/e2e/config/ibmcloud-e2e-vpc.yaml
Updates cluster-api to v1.3.3
Fixes #
```release-note
Update cluster-api to v1.3.3
```
=> Update cluster-api to v1.3.3

scripts/ci-e2e.sh, templates/cluster-template-powervs.yaml, test/e2e/config/ibmcloud-e2e-powervs.yaml, test/e2e/data/templates/cluster-template-powervs-md-remediation/kustomization.yaml, test/e2e/data/templates/cluster-template-powervs-md-remediation/mhc-kcp-powervs.yaml, test/e2e/data/templates/cluster-template-powervs-md-remediation/mhc-md-powervs.yaml, test/e2e/data/templates/cluster-template-powervs-md-remediation/patches/mhc-label.yaml
- PVS e2e related changes
- Add KCP remediation template
- Add md remediation label patch
Fixes #
```release-note
PVS e2e related changes
```
=> PVS e2e related changes

cmd/capibmadm/cmd/powervs/network/create.go, cmd/capibmadm/cmd/powervs/network/network.go, cmd/capibmadm/cmd/powervs/powervs.go, cmd/capibmadm/cmd/root.go
Initial implementation for capibmadm is done via PR: https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/1027, This PR updates few function names for better readibility.
Fixes #
```release-note
```
=> Update the function names

cmd/capibmadm/clients/powervs/client.go, cmd/capibmadm/cmd/powervs/network/list.go, cmd/capibmadm/cmd/powervs/network/network.go, cmd/capibmadm/cmd/powervs/network/type.go, cmd/capibmadm/cmd/powervs/powervs.go, cmd/capibmadm/options/options.go, docs/book/src/topics/capibmadm/powervs/index.md, docs/book/src/topics/capibmadm/powervs/network.md, go.mod, go.sum
Add support for listing PowerVS network.
Client code for authentication and printing results.
Fixes #
```release-note
```
=> Add initial code for powervs network list

cmd/capibmadm/cmd/powervs/network/type.go, hack/boilerplate/boilerplate.py, hack/boilerplate/boilerplate_test.py
- fix verify-boilerplate to catch errors in CI
Fixes #
```release-note
fix verify-boilerplate to catch errors in CI
```
=> fix verify-boilerplate to catch errors in CI

cmd/capibmadm/cmd/vpc/image/image.go, cmd/capibmadm/cmd/vpc/image/list.go, cmd/capibmadm/cmd/vpc/image/type.go, cmd/capibmadm/cmd/vpc/vpc.go, cmd/capibmadm/options/options.go
Add capibmadm vpc image list command.
Fixes #
```release-note
```
=> Add capibmadm vpc image list command

docs/book/src/SUMMARY.md, docs/book/src/topics/capibmadm/index.md, docs/book/src/topics/capibmadm/vpc/image.md, docs/book/src/topics/capibmadm/vpc/index.md
=> Add doc for vpc image list cmd

.github/dependabot.yml
- exclude go modules for dependbot
Fixes #1133 
```release-note
exclude go modules for dependbot
```
=> exclude go modules for dependbot

go.mod, go.sum, hack/tools/go.mod, hack/tools/go.sum, test/e2e/config/ibmcloud-e2e-powervs.yaml, test/e2e/config/ibmcloud-e2e-vpc.yaml
- Update cluster-api to 1.3.5
Fixes #
```release-note
Update cluster-api to 1.3.5
```
=> Update cluster-api to 1.3.5

docs/book/src/machine-images/index.md, docs/book/src/machine-images/vpc.md
- Publish VPC image for k8s 1.25.6 version
Fixes #
```release-note
Publish VPC image for k8s 1.25.6 version
```
=> Publish VPC image for k8s 1.25.6 version

docs/book/src/machine-images/powervs.md
- Publish PVS image for k8s 1.25.6 version
Fixes #
```release-note
Publish PVS image for k8s 1.25.6 version
```
=> Publish PVS image for k8s 1.25.6 version

docs/book/src/machine-images/powervs.md, docs/book/src/machine-images/vpc.md
- Publish PVS and VPC image for k8s 1.26.2 version
Fixes #
```release-note
Publish PVS and VPC image for k8s 1.26.2 version
```
=> Publish PVS and VPC image for k8s 1.26.2 version

.github/dependabot.yml, hack/ccm/Dockerfile
- Fix missing golang update by dependbot
Fixes #
```release-note
Fix missing golang update by dependbot
```
=> Fix missing golang update by dependbot

cmd/capibmadm/cmd/powervs/key/key.go, cmd/capibmadm/cmd/powervs/key/list.go, cmd/capibmadm/cmd/powervs/key/type.go, docs/book/src/topics/capibmadm/powervs/index.md, docs/book/src/topics/capibmadm/powervs/key.md
Add cmd for ssh key list.
Fixes #
```release-note
```
=> Add cmd for ssh key list

docs/book/src/developer/build-images.md, docs/book/src/machine-images/powervs.md, docs/book/src/machine-images/vpc.md, docs/book/src/topics/vpc/prerequisites.md, docs/book/src/topics/vpc/uploading-an-image.md
- Enhance image building instructions
Fixes #1149 
```release-note
Enhance image building instructions
```
=> Enhance image building instructions

api/v1beta2/ibmpowervsclustertemplate_webhook.go, api/v1beta2/ibmpowervsclustertemplate_webhook_test.go, api/v1beta2/suite_test.go, cloud/scope/suite_test.go, config/webhook/manifests.yaml, controllers/suite_test.go, main.go
Add Webhooks for IBMPowerVSClusterTemplate
Fixes #
Fix https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/975
```release-note
Add Webhooks for IBMPowerVSClusterTemplate
```
=> Add Webhooks for IBMPowerVSClusterTemplate

Dockerfile, Makefile, cmd/capibmadm/cmd/powervs/powervs.go, cmd/capibmadm/cmd/root.go, cmd/capibmadm/cmd/version/doc.go, cmd/capibmadm/cmd/version/version.go, cmd/capibmadm/cmd/vpc/vpc.go, go.mod, version/version.go
- Add `capibmadm` tool related targets
- Introduce version package
Output :
```
% ./capibmadm version -o short
v0.5.0-alpha.0.54-c4d887210d55c2-dirty
% ./capibmadm version -o yaml 
clientversion:
major: "0"
minor: "5"
gitversion: v0.5.0-alpha.0.54-c4d887210d55c2-dirty
gitcommit: c4d887210d55c27ff301def53f55b7ce044a4f4d
gittreestate: dirty
builddate: "2023-04-11T18:10:41Z"
goversion: go1.19.6
compiler: gc
platform: darwin/amd64
% ./capibmadm version -o json
{
"ibmcloudProviderVersion": {
"major": "0",
"minor": "5",
"gitVersion": "v0.5.0-alpha.0.54-c4d887210d55c2-dirty",
"gitCommit": "c4d887210d55c27ff301def53f55b7ce044a4f4d",
"gitTreeState": "dirty",
"buildDate": "2023-04-11T18:10:41Z",
"goVersion": "go1.19.6",
"compiler": "gc",
"platform": …
```
=> Add capibmadm tool related targets

test/e2e/data/cni/calico/calico.yaml
Update calico spec in e2e
Fixes #1059 
```release-note
Update calico spec in e2e
```
=> update calico spec used by e2e tests

metadata.yaml, test/e2e/config/ibmcloud-e2e-powervs.yaml, test/e2e/config/ibmcloud-e2e-vpc.yaml
Update release version 0.5
Fixes #
```release-note
Update release version 0.5
```
=> Update release version 0.5

Dockerfile, Makefile
- Fix docker buildx usage
Fixes #1191 
```release-note
Fix docker buildx usage
```
=> Fix docker buildx usage

cloudbuild.yaml
- Bump gcb-docker-gcloud from v20221214-1b4dd4d69a to v20230424-910a2a439d
Fixes #
```release-note
Bump gcb-docker-gcloud from v20221214-1b4dd4d69a to v20230424-910a2a439d
```
=> Bump gcb-docker-gcloud from v20221214-1b4dd4d69a to v20230424-910a2a439d

Makefile, hack/init-buildx.sh
- Add init-buildx script for better log description
Fixes #
```release-note
Add init-buildx script for better log description
```
=> Add init-buildx script for better log description

hack/init-buildx.sh
- Dump docker related data for buildx debug
Fixes #
```release-note
Dump docker related data for buildx debug
```
=> Dump docker related data for buildx debug

Makefile, cloudbuild.yaml, hack/init-buildx.sh, scripts/ci-make.sh
- Bump gcb image
- Improve buildx flow
Fixes #
```release-note
Bump gcb image and improve buildx flow
```
=> Bump gcb image and improve buildx flow

Makefile, cloudbuild.yaml
- update machineType in cloudbuild
- Fix buildx platform list
Fixes #
```release-note
- update machineType in cloudbuild
- Fix buildx platform list
```
=> update machineType in cloudbuild

metadata.yaml, test/e2e/config/ibmcloud-e2e-powervs.yaml, test/e2e/config/ibmcloud-e2e-vpc.yaml
Fixes #1237 
```release-note
```
=> Update metadata version to v0.6.0

.gitignore, scripts/ci-e2e.sh
Build and use capibmadm from main for E2E testing.
Fixes #1255 
```release-note
Build and use capibmadm from main for E2E
```
=> Build and use capibmadm from main for E2E

Dockerfile, Makefile, hack/boilerplate/boilerplate.Dockerfile.txt, hack/ccm/Dockerfile
- Update Dockerfile syntax to 1.5
Fixes #
```release-note
Update Dockerfile syntax to 1.5
```
=> Update Dockerfile syntax to 1.5

go.mod, go.sum, hack/tools/go.mod, hack/tools/go.sum, test/e2e/config/ibmcloud-e2e-powervs.yaml, test/e2e/config/ibmcloud-e2e-vpc.yaml
Update cluster-api to v1.4.3
Fixes #1257 
```release-note
Update cluster-api to v1.4.3
```
=> Update cluster-api to v1.4.3

docs/book/src/machine-images/powervs.md, docs/book/src/machine-images/vpc.md
- Publish PVS and VPC image for k8s 1.27.2 version
Fixes #
```release-note
Publish PVS and VPC image for k8s 1.27.2 version
```
=> Publish PVS and VPC image for k8s 1.27.2 version

scripts/ci-e2e.sh, test/e2e/config/ibmcloud-e2e-powervs.yaml, test/e2e/config/ibmcloud-e2e-vpc.yaml
- Use k8s 1.27.2 images for e2e tests
Fixes #
```release-note
Use k8s 1.27.2 images for e2e tests
```
=> Use k8s 1.27.2 images for e2e tests

hack/ensure-kind.sh
- Update KIND to v0.20.0
Fixes #1292
```release-note
Update KIND to v0.20.0
```
=> Update KIND to v0.20.0

Makefile
- update kubebuilder tools to 1.27.x
Fixes #
```release-note
update kubebuilder tools to 1.27.x
```
=> update kubebuilder tools to 1.27.x

docs/book/book.toml, docs/book/src/introduction.md, docs/book/theme/css/custom.css
- book: update refs to release specific books
Fixes #
```release-note
book: update refs to release specific books
```
=> book: update refs to release specific books

go.mod, go.sum, hack/tools/go.mod, hack/tools/go.sum, test/e2e/config/ibmcloud-e2e-powervs.yaml, test/e2e/config/ibmcloud-e2e-vpc.yaml
- Update cluster-api to v1.5.0
Fixes #
```release-note
Update cluster-api to v1.5.0
```
=> Update cluster-api to v1.5.0

hack/tools/Makefile
- fix build tags
Fixes #1316 [release-0.5]
```release-note
fix build tags
```
=> [release-0.5] fix build tags

Makefile, scripts/fetch_ext_bins.sh
- update kubebuilder tools to 1.25.x
Fixes #
```release-note
update kubebuilder tools to 1.25.x
```
=> [Release-0.4] update kubebuilder tools to 1.25.x

scripts/fetch_ext_bins.sh
- Fix k8s version of kubebuilder tools
Fixes #
```release-note
Fix k8s version of kubebuilder tools
```
=> [Release-0.5] Fix k8s version of kubebuilder tools

scripts/fetch_ext_bins.sh
- Fix k8s version of kubebuilder tools
Fixes #
```release-note
Fix k8s version of kubebuilder tools
```
=> Fix k8s version of kubebuilder tools

docs/book/book.toml, docs/book/src/introduction.md, docs/book/theme/css/custom.css
- book: update refs to release specific books (#1288)
Fixes #
```release-note
book: update refs to release specific books
```
=> [release-0.4] book: update refs to release specific books

docs/book/src/developer/dependencies.md
- Part of #1293 
- update dependencies list with IBM packages
Fixes #
```release-note
update dependencies list with IBM packages
```
=> update dependencies list with IBM packages

test/e2e/data/templates/cluster-template-powervs-md-remediation/kustomization.yaml
- disable KCP remediation
- This change should fix the CI related failures, KCP remediation is causing CPs to stuck in recreate cycle resulting in timeout issues causing CI failure.
- This is a preventive measure to get CI up and running again for green signals, while we continue investigation on KCP remediation flow post CAPI v1.5 update. 
Fixes #
```release-note
disable KCP remediation
```
=> disable KCP remediation

cmd/capibmadm/cmd/powervs/network/list.go, go.mod, go.sum
- Bump github.com/IBM-Cloud/power-go-client from 1.2.4 to 1.3.0
Fixes #
```release-note
Bump github.com/IBM-Cloud/power-go-client from 1.2.4 to 1.3.0
```
=> Bump github.com/IBM-Cloud/power-go-client from 1.2.4 to 1.3.0

README.md
- add v0.5.x to compatibility matrix
Fixes #
```release-note
add v0.5.x to compatibility matrix
```
=> add v0.5.x to compatibility matrix

netlify.toml
- Fix netlify redirects
Fixes #
```release-note
Fix netlify redirects
```
=> Fix netlify redirects

docs/book/src/introduction.md
- Drop release-0.3 from book docs
Fixes #
```release-note
Drop release-0.3 from book docs
```
=> Drop release-0.3 from book docs

Makefile
This change will verify if the cluster templates  are updated when the generate target is run on `make verify`.
Fixes #
```release-note
Run generate-templates as a part of make generate
```
=> Run generate-templates as a part of make generate

test/e2e/e2e_test.go
- Add waiter functions for control-plane
This function is introduced to give additional breather for e2e flow to avoid failure due to timeout issue while applying CNI.
Note - we shall observe the future CI runs to learn its impact.
Fixes #
```release-note
Add waiter functions for control-plane
```
=> Add waiter functions for control-plane

config/manager/manager.yaml
Removes deprecated flag `--powervs-provider-id-fmt`.
Fixes #1408 
```release-note
Remove deprecated flag powervs-provider-id-fmt
```
=> Remove deprecated flag powervs-provider-id-fmt

test/e2e/e2e_test.go
- Revert commit: Add waiter functions for control-plane
The above code commit did not fix the intended bug/issue.
Fixes #1403 
```release-note
Revert commit: Add waiter functions for control-plane
```
=> Revert commit: Add waiter functions for control-plane

docs/book/src/topics/powervs/clusterclass-cluster.md, docs/book/src/topics/vpc/load-balancer.md
- Minor nit: fix template names
Fixes #
```release-note
Minor nit: fix template names
```
=> Minor nit: fix template names

docs/book/src/developer/tilt-with-podman.md
This PR adds documentation to migrate to Podman in macOS.
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/1371
```release-note
```
=> Added instructions needed to be run on macOS for migrating to Podman.

go.mod, go.sum, hack/tools/go.mod, hack/tools/go.sum, test/e2e/config/ibmcloud-e2e-powervs.yaml, test/e2e/config/ibmcloud-e2e-vpc.yaml
Update cluster-api to v1.5.2
Fixes #
```release-note
Update cluster-api to v1.5.2
```
=> Update cluster-api to v1.5.2

go.mod, go.sum, hack/tools/go.mod, hack/tools/go.sum, test/e2e/config/ibmcloud-e2e-powervs.yaml, test/e2e/config/ibmcloud-e2e-vpc.yaml
Update cluster-api to v1.4.7
Fixes #
```release-note
Update cluster-api to v1.4.7
```
=> [release-0.5] Update cluster-api to v1.4.7

Dockerfile, hack/ccm/Dockerfile
Bumps golang from 1.20.8 to 1.20.9
Fixes #
```release-note
Update golang to 1.20.9
```
=> Update golang to 1.20.9

metadata.yaml
Manual cherrypick of #1441 
Fixes #
```release-note
```
=> [release-0.5] fix: remove trailing whitespace from metadata.yaml

cmd/capibmadm/cmd/version/version.go, go.mod
Fixes #1456 
/kind cleanup
```release-note
NONE
```
=> Replace gopkg.in/yaml.v2 with sigs.k8s.io/yaml

Dockerfile, hack/ccm/Dockerfile
- Bump golang from 1.20.9 to 1.20.10
Fixes #
```release-note
Bump golang from 1.20.9 to 1.20.10
```
=> Bump golang from 1.20.9 to 1.20.10

test/e2e/data/shared/metadata.yaml
Update test metadata.yaml with cluster-api v1.6
Fixes #1475 
```release-note
Update test metadata.yaml with cluster-api v1.6
```
=> Update test metadata.yaml with cluster-api v1.6

docs/book/src/topics/vpc/load-balancer.md
- Update doc commands with correct template references
Fixes #1494 
```release-note
Update doc commands with correct template references
```
=> Update doc commands with correct template references

Dockerfile, Makefile, hack/ccm/Dockerfile
Bump golang from 1.20.10 to 1.20.11
Fixes #
```release-note
Bump golang from 1.20.10 to 1.20.11
```
=> Bump golang from 1.20.10 to 1.20.11

test/e2e/suite_test.go
This PR checks if controllers are deployed successfully in smoke-test
Fixes #1482 
```release-note
```
=> Check if controllers are deployed successfully in smoke-test

docs/book/src/machine-images/powervs.md, docs/book/src/machine-images/vpc.md
- Publish PVS and VPC image for k8s 1.28.4 version
Fixes #
```release-note
Publish PVS and VPC image for k8s 1.28.4 version
```
=> Publish PVS and VPC image for k8s 1.28.4 version

Dockerfile, Makefile, hack/ccm/Dockerfile
- Bump golang to v1.20.12
Fixes #
```release-note
Bump golang to v1.20.12
```
=> Bump golang to v1.20.12

metadata.yaml, test/e2e/config/ibmcloud-e2e-powervs.yaml, test/e2e/config/ibmcloud-e2e-vpc.yaml
Update version references to 0.7.0 in metadata.yaml and test config files.
Fixes #
```release-note
Update version references to 0.7.0
```
=> Update version references to 0.7.0

.github/workflows/weekly-security-scan.yaml, README.md
- Update release versions in security scan workflow
Fixes #
```release-note
Update release versions in security scan workflow
```
=> Update release versions in security scan workflow

hack/tools/go.mod, hack/tools/go.sum, pkg/cloud/services/powervs/mock/powervs_generated.go, pkg/cloud/services/vpc/mock/vpc_generated.go
Bump go.uber.org/mock from 0.3.0 to 0.4.0 in /hack/tools
Fixes #
```release-note
Bump go.uber.org/mock from 0.3.0 to 0.4.0 in /hack/tools
```
=> Bump go.uber.org/mock from 0.3.0 to 0.4.0 in /hack/tools

docs/book/src/introduction.md
- book: update refs to release-0-7 specific book
Fixes #
```release-note
book: update refs to release-0-7 specific book
```
=> book: update refs to release-0-7 specific book

docs/book/src/SUMMARY.md, docs/book/src/developer/index.md, docs/book/src/developer/release-support-guidelines.md
- Add support and release content to CAPIBM book doc
Fixes #
```release-note
Add support and release content to CAPIBM book doc
```
=> [release-0.6] Add support and release content to CAPIBM book doc

docs/book/src/developer/release-support-guidelines.md
- Update release support data
Fixes #
```release-note
Update release support data
```
=> Update release support data

hack/ccm/Makefile
=> Update cloud-provider-powervs commit to create latest ccm image

templates/addons/crs-powervs.yaml, templates/addons/crs.yaml, templates/cluster-template-powervs-cloud-provider.yaml, templates/cluster-template-powervs-clusterclass.yaml, templates/cluster-template-vpc-clusterclass.yaml, templates/cluster-template.yaml
=> Update tempaltes to use latest ccm image

scripts/ci-e2e.sh
This PR tags the power-haas plugin to a specific version rather than installing the latest version available. This will be helpful in avoiding CI failures when version updates could introduce breaking changes.
Fixes #
```release-note
Tag power-iaas plugin to a specific version
```
=> Tag power-iaas plugin to a specific version

scripts/ci-e2e.sh
This PR tags the power-haas plugin to a specific version rather than installing the latest version available. This will be helpful in avoiding CI failures when version updates could introduce breaking changes.
Fixes #
```release-note
Tag power-iaas plugin to a specific version
```
=> [release-0.6]Tag power-iaas plugin to a specific version

scripts/ci-e2e.sh
This PR tags the power-haas plugin to a specific version rather than installing the latest version available. This will be helpful in avoiding CI failures when version updates could introduce breaking changes.
Fixes #
```release-note
Tag power-iaas plugin to a specific version
```
=> [release-0.7]Tag power-iaas plugin to a specific version

cloud/scope/powervs_image.go
=> Support service instance id for IBMPowerVSImage

Dockerfile, Makefile, hack/ccm/Dockerfile
- [release-0.6] bump golang to v1.21.9
Fixes #
```release-note
[release-0.6] bump golang to v1.21.9
```
=> [release-0.6] bump golang to v1.21.9

Dockerfile, Makefile, hack/ccm/Dockerfile
- [release-0.7] bump golang to v1.21.9
Fixes #
```release-note
[release-0.7] bump golang to v1.21.9
```
=> [release-0.7] bump golang to v1.21.9

Makefile, hack/ccm/Makefile
Bump golang to v1.21.10
Fixes #
```release-note
Bump golang to v1.21.10
```
=> Bump golang to v1.21.10

metadata.yaml
cherry-pick of https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/1794
```release-note
```
=> fix: remove whitespaces from metadata.yaml

metadata.yaml, test/e2e/config/ibmcloud-e2e-powervs.yaml, test/e2e/config/ibmcloud-e2e-vpc.yaml
Update version references to 0.9.0 in `metadata.yaml` and test config files.
Fixes #
```release-note
Update version references to 0.9.0
```
=> Update version references to 0.9.0

.github/workflows/weekly-security-scan.yaml
Update release versions for weekly security scan
Fixes #
```release-note
Update release versions for weekly security scan
```
=> Update release versions for weekly security scan

docs/book/src/machine-images/powervs.md, scripts/ci-e2e.sh, test/e2e/config/ibmcloud-e2e-powervs.yaml
Bump PowerVS CI to k8s v1.29
Fixes #1782 
```release-note
Bump PowerVS CI to k8s v1.29
```
=> Bump PowerVS CI to k8s v1.29

Makefile
- Fix trivy analysis reported issues
- bump golang to v1.21.11
Fixes #
```release-note
Fix trivy analysis reported issues
```
=> Fix trivy analysis reported issues

Makefile, scripts/fetch_ext_bins.sh
- update kubebuilder tools to 1.29.3
Fixes #
```release-note
update kubebuilder tools to 1.29.3
```
=> update kubebuilder tools to 1.29.3

Makefile, hack/ccm/Makefile
Bump golang to 1.21.11
Fixes #
```release-note
Bump golang to 1.21.11
```
=> Bump golang to 1.21.11

Makefile
- Fix trivy analysis reported issues
- Bump golang to v1.21.11
Fixes #
```release-note
Fix trivy analysis reported issues
```
=> [release-0.7]Fix trivy analysis reported issues

Makefile, hack/ccm/Makefile
Update golang version to 1.21.12 to fix trivy vulnerabilities
Fixes #
```release-note
Update golang version to 1.21.12
```
=> Update golang version to 1.21.12

Dockerfile, Makefile, hack/ccm/Dockerfile
- Update golang version to 1.21.12
Fixes #
```release-note
Update golang version to 1.21.12
```
=> [release-0.7] Update golang version to 1.21.12

README.md, docs/book/src/introduction.md
Update docs with references to release-0.8
Fixes #
```release-note
Update docs with references to release-0.8
```
=> Update docs with references to release-0.8

.github/dependabot.yml
Track and update networking-go-sdk and trivy packages via dependabot now that we moved to go 1.22
Fixes #1811 
```release-note
Track and update networking-go-sdk and trivy packages via dependabot
```
=> Track and update networking-go-sdk and trivy packages via dependabot

.github/workflows/weekly-security-scan.yaml
- Bump actions version
ref- https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
Fixes #
```release-note
Bump actions version
```
=> Bump actions version

Makefile, hack/ccm/Makefile, netlify.toml
Bump golang version to 1.22.7
Fixes #
```release-note
Bump golang version to 1.22.7
```
=> Bump golang version to 1.22.7

cloud/scope/powervs_cluster.go, cloud/scope/powervs_cluster_test.go
This PR adds UT for powervs_cluster.go files
Fixes # Partially fixes https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/1818
```release-note
```
=> Add UT for powervs_cluster file

.gitignore
Ignores unit test coverage files
Fixes #
```release-note
Ignore unit test coverage files
```
=> Ignore unit test coverage files

cloud/scope/vpc_cluster.go
Move the status update after creating a vpc to occur prior to attempting to tag the vpc. This will align with other resource reconciliation paths.
**What this PR does / why we need it**:  Align VPC resource initial status to other VPC resources
Fixes #
```release-note
Move VPC set status logic to follow pattern used by other VPC resources, just prior to tagging.
```
=> VPC: Move vpc status update before tagging

scripts/ci-e2e.sh
Replace service-target with worskpace after power-iaas plugin update
Fixes #
```release-note
Replace service-target with worskpace after power-iaas plugin update
```
=> [release-0.7]Replace service-target with worskpace after power-iaas plugin update

Makefile, hack/ccm/Makefile, netlify.toml
Update golang version to 1.22.8
Fixes #
```release-note
Update golang version to 1.22.8
```
=> Update golang version to 1.22.8

cloud/scope/powervs_machine.go
Tested COS service endpoint override, found some places that need additional code, and this PR ensures the overridden COS endpoint is indeed used for bootstrap ignition. Verified the bootstrap VM boots up with the ignition on the custom endpoint specified in `install-config.yaml` like below;
```
serviceEndpoints:
- name: cos
url: https://s3.direct.jp-osa.cloud-object-storage.appdomain.cloud
```
(Note above `.direct` in URL is specifically for a Disconnected scenario, and a VPE allowing the traffic needs to be in place beforehand.)
=> ServiceEndpoint overrides saved and used correctly for ignition URL

cloud/scope/powervs_cluster_test.go
Add UT for ReconcileVPC, createVPC, checkVPC, getVPCByName and GetServiceName functions
Partially fixes #1818
=> Add UT for ReconcileVPC and its subfunctions

cloud/scope/powervs_cluster_test.go
Add UT for ReconcileVPCSubnet, SetVPCSubnetStatus, checkVPCSubnet, createVPCSubnet functions
Partially fixes https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/1818
=> Add UT for ReconcileVPCSubnet and its subfunctions

controllers/ibmpowervscluster_controller_test.go
Partially Fixes #1818 
```release-note
```
=> Added UT for reconcilePowerVSResources function

cloud/scope/powervs_cluster_test.go
It adds UTs forReconcileTransitGateway function 
Fixes # https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/1818
```release-note
Add UT for ReconcileTransitGateway
```
=> Add UT for ReconcileTransitGateway

cloud/scope/powervs_cluster_test.go
Adds UT for DeleteLoadbalancer,DeleteTransitGateway,DeleteVPC,DeleteVPCSubnet,DeleteVPCSecurityGroups functions
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/1818
```release-note
```
=> Added UT for powervs_cluster delete functions

cloud/scope/common_test.go, cloud/scope/powervs_machine.go, cloud/scope/powervs_machine_test.go
Code coverage increase
No change in any image version or functionality
=> UT update for powervs machine

metadata.yaml, test/e2e/config/ibmcloud-e2e-powervs.yaml, test/e2e/config/ibmcloud-e2e-vpc.yaml
Update version references to 0.10.0
Fixes #
```release-note
Update version references to 0.10.0
```
=> Update version references to 0.10.0

Makefile, hack/ccm/Makefile, netlify.toml
Update golang version to 1.22.9
Fixes #
```release-note
Update golang version to 1.22.9
```
=> Update golang version to 1.22.9

.github/workflows/weekly-security-scan.yaml
Update release branch versions for weekly security scan
Fixes #
```release-note
Update release branch versions for weekly security scan
```
=> Update release branch versions for weekly security scan

go.mod, hack/tools/go.mod
**What this PR does / why we need it**: Fixes toolchain version to the go version used in our builds
Fixes #2048 
```release-note
```
=> Set toolchain in go.mod

docs/book/src/developer/e2e.md, docs/book/src/developer/release-support-guidelines.md
- Update release support data
Fixes #
```release-note
Update release support data
```
=> [release-0.8] Update release support data

README.md, docs/book/src/introduction.md
- Update docs with references to release-0.9
Fixes #
```release-note
Update docs with references to release-0.9
```
=> [release-0.9] Update docs with references to release-0.9

README.md, docs/book/src/introduction.md
- Update docs with references to release-0.9
Fixes #
```release-note
Update docs with references to release-0.9
```
=> Update docs with references to release-0.9

docs/book/src/introduction.md
- Update docs with references to release-0.8
Fixes #
```release-note
Update docs with references to release-0.8
```
=> [release-0.8] Update docs with references to release-0.8

cloudbuild.yaml, hack/ccm/cloudbuild.yaml
- bump gcr.io/k8s-staging-test-infra/gcb-docker-gcloud to v20241111-71c32dbdcc
Fixes #2098 
```release-note
bump gcr.io/k8s-staging-test-infra/gcb-docker-gcloud to v20241111-71c32dbdcc
```
=> bump gcr.io/k8s-staging-test-infra/gcb-docker-gcloud to v20241111-71c32dbdcc

cloudbuild.yaml, hack/tools/go.mod
Latest gcb-docker-gcloud  is failing with the following error:
```
72a1c197f016:/workspace# go version
go version go1.22.9 linux/amd64
72a1c197f016:/workspace# python --version
Python 3.12.7
72a1c197f016:/workspace# gsutil 
Error: gsutil requires Python version 2.7 or 3.5-3.11, but a different version is installed.
You are currently running Python 3.12
Follow the steps below to resolve this issue:
1. Switch to Python 3.5-3.11 using your Python version manager or install an appropriate version.
2. If you are unsure how to manage Python versions, visit [https://cloud.google.com/storage/docs/gsutil_install#specifications] for detailed instructions.
```
As the older version of gcb-docker-gcloud does't contain the later version of golang, hence sticking …
=> Pin to working golang and gcb-docker-gcloud version

hack/tools/go.mod
- pin go version to 1.22.9 in tools
Fixes #
```release-note
pin go version to 1.22.9 in tools
```
=> pin go version to 1.22.9 in tools

Makefile, hack/ccm/Makefile, netlify.toml
Bump golang version to 1.22.10
Fixes #
```release-note
Bump golang version to 1.22.10
```
=> Bump golang version to 1.22.10

.github/ISSUE_TEMPLATE/cluster_api_version_update.md, .github/ISSUE_TEMPLATE/release.md
Add templates for cluster-api version update and release tracker
Fixes #
```release-note
Add templates for cluster-api version update and release tracker
```
=> Add templates for cluster-api version update and release tracker

docs/book/src/machine-images/powervs.md
- Fix powervs machine image link
Fixes #
```release-note
Fix powervs machine image link
```
=> [release-0.9] Fix powervs machine image link

hack/ccm/Makefile
This PR updates the PowerVS Cloud controller commit hash to the latest available in `openshift/cloud-provider-powervs` - main
```release-note
NONE
```
=> Update the commit-hash for PowerVS Cloud Controller

Makefile, hack/ccm/Makefile, netlify.toml
- Bump golang to v1.22.12
- Fix security vulnerabilities
Fixes #
```release-note
Bump golang to v1.22.12
```
=> Bump golang to v1.22.12

templates/addons/crs-powervs.yaml, templates/addons/crs.yaml, templates/cluster-template-powervs-clusterclass.yaml, templates/cluster-template-powervs-create-infra.yaml, templates/cluster-template-powervs.yaml, templates/cluster-template-vpc-clusterclass.yaml, templates/cluster-template.yaml, test/e2e/data/templates/cluster-template-powervs-md-remediation.yaml, test/e2e/data/templates/cluster-template-vpc.yaml
- update powervs-cloud-controller image tag
Fixes #
```release-note
update powervs-cloud-controller image tag
```
=> update powervs-cloud-controller image tag

.github/ISSUE_TEMPLATE/release.md
Fix release issue template description
Fixes #2195 
```release-note
Fix release issue template description
```
=> Fix release issue template description

.github/workflows/weekly-security-scan.yaml, README.md, docs/book/src/developer/release-support-guidelines.md, metadata.yaml, test/e2e/config/ibmcloud-e2e-powervs.yaml, test/e2e/config/ibmcloud-e2e-vpc.yaml
- Update version references to 0.11.0
- Update release branch versions for weekly security scan
- Update release support data
Fixes #
```release-note
Post v0.10.0 release housekeeping
```
=> Post v0.10.0 release housekeeping

README.md, docs/book/src/developer/release-support-guidelines.md
- Update docs with v0.10.0 references
Fixes #
```release-note
Update docs with v0.10.0 references
```
=> [release-0.10] Update docs with v0.10.0 references

docs/book/src/introduction.md
- Add release-0-10 book link
Fixes #
```release-note
Add release-0-10 book link
```
=> Add release-0-10 book link

hack/ccm/Makefile, templates/addons/crs-powervs.yaml, templates/addons/crs.yaml, templates/cluster-template-powervs-clusterclass.yaml, templates/cluster-template-powervs-create-infra.yaml, templates/cluster-template-powervs.yaml, templates/cluster-template-vpc-clusterclass.yaml, templates/cluster-template.yaml, test/e2e/data/templates/cluster-template-powervs-md-remediation.yaml, test/e2e/data/templates/cluster-template-vpc.yaml
Recently, the PowerVS CI has started failing after change in CCM image as the commit picked was missing PowerVS code changes. This PR add the relevant commit.
Fixes #2211 
```release-note
Update CCM image to fix the PowerVS CI
```
=> Update CCM image to fix the PowerVS CI

.github/ISSUE_TEMPLATE/release.md
Update the release issue template
Fixes #
```release-note
Update the release issue template
```
=> Update the release issue template

api/v1beta2/suite_test.go, cloud/scope/suite_test.go, controllers/suite_test.go, hack/tools/go.mod, hack/tools/go.sum
Fixes CI failing test: https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_cluster-api-provider-ibmcloud/2172/pull-cluster-api-provider-ibmcloud-test/1897220961703301120
Fixes #
```release-note
```
=> Bump honnef.co/go/tools

hack/ccm/Dockerfile, hack/ccm/Makefile, hack/ccm/cloudbuild.yaml
- streamline the CCM image build process
Fixes #2210 
```release-note
streamline the CCM image build process
```
=> streamline the CCM image build process

hack/ccm/Dockerfile
- fix platform flags in ccm build
Fixes #
```release-note
fix platform flags in ccm build
```
=> fix platform flags in ccm build

api/v1beta2/suite_test.go, cloud/scope/suite_test.go, controllers/suite_test.go, hack/tools/go.mod, hack/tools/go.sum
- Bump honnef.co/go/tools
Fixes #
```release-note
Bump honnef.co/go/tools
```
=> [release-0.9] Bump honnef.co/go/tools

docs/book/src/introduction.md
This PR updates the community meeting zoom link and meeting time in CAPIBM book.
Fixes #
```release-note
Update community zoom meeting link and time in book
```
=> Update meeting time and zoom link

.trivyignore
- According to govulncheck we are not using code that is affected by CVE 2025 22870, so ignoring it
Fixes #2268 
```release-note
Ignore CVE-2025-22870
```
=> [release-0.10] Ignore CVE-2025-22870

go.mod, go.sum, pkg/cloud/services/utils/accounts.go
- fix GO-2025-3553 Vulnerability
ref - https://pkg.go.dev/vuln/GO-2025-3553
Fixes #
```release-note
fix GO-2025-3553 Vulnerability
```
=> fix GO-2025-3553 Vulnerability

go.mod, go.sum, pkg/cloud/services/utils/accounts.go
- fix [GO-2025-3553](https://pkg.go.dev/vuln/GO-2025-3553) Vulnerability
Fixes #
```release-note
fix GO-2025-3553 Vulnerability
```
=> [release-0.9] fix GO-2025-3553 Vulnerability

hack/ccm/Makefile
This PR update the commit of cloud-provider-powervs to build the image with latest commit
Fixes #
```release-note
Update cloud-provider-powervs commit to latest to builld new ccm image
```
=> Update cloud-proivder-powervs commit to build new ccm image

go.mod, go.sum, hack/tools/go.mod, hack/tools/go.sum, test/e2e/config/ibmcloud-e2e-powervs.yaml, test/e2e/config/ibmcloud-e2e-vpc.yaml
Update cluster-api to v1.10.1
Fixes part of #2307
```release-note
Update cluster-api to v1.10.1
```
=> Update cluster-api to v1.10.1

hack/ccm/Makefile, hack/verify-container-images.sh
- Update cloud-proivder-powervs commit
- Include CCM image in trivy scan flow
Fixes #
```release-note
Update cloud-proivder-powervs commit
```
=> Update cloud-proivder-powervs commit

templates/addons/crs-powervs.yaml, templates/addons/crs.yaml, templates/cluster-template-powervs-clusterclass.yaml, templates/cluster-template-powervs-create-infra.yaml, templates/cluster-template-powervs.yaml, templates/cluster-template-vpc-clusterclass.yaml, templates/cluster-template.yaml, test/e2e/data/templates/cluster-template-powervs-md-remediation.yaml, test/e2e/data/templates/cluster-template-vpc.yaml
- Update cloud-controller-manager container image to latest image
Fixes #
```release-note
Update cloud-controller-manager container image to latest image
```
=> Update cloud-controller-manager container image to latest image

docs/book/src/machine-images/powervs.md, docs/book/src/machine-images/vpc.md
- drop older k8s images
Fixes #
```release-note
drop older k8s images
```
=> drop older k8s images

docs/book/src/developer/release.md
This PR contains the changes to include the release issue template that serves as a checklist/tracker for the tasks that are expected to be done post release.
Fixes #2152
/kind documentation
```release-note
Update documentation to contain post-release tasks
```
=> Update documentation to contain post-release tasks

templates/cluster-template.yaml, templates/cluster-template/md.yaml, test/e2e/data/templates/cluster-template-vpc.yaml
- revert additionalVolumes from templates
Fixes #
```release-note
revert additionalVolumes from templates
```
=> revert additionalVolumes from templates

docs/book/src/user/troubleshooting.md
This PRs update trouble shooting guide with instructions to debug CCM issues, It will be helpful when the Machines are struck in Provisioned state.
Fixes #2250
```release-note
Update trouble shooting guide with instructions to debug CCM issues
```
=> Update trouble shooting guide with instructions to debug CCM issues

docs/book/src/machine-images/powervs.md, docs/book/src/machine-images/vpc.md
- update k8s machine images
Fixes #
```release-note
update k8s machine images
```
=> [release-0.10] update k8s machine images

docs/book/src/machine-images/powervs.md, docs/book/src/machine-images/vpc.md
- update k8s machine images
Fixes #
```release-note
update k8s machine images
```
=> [release-0.9] update k8s machine images

docs/book/src/machine-images/powervs.md, docs/book/src/machine-images/vpc.md
- update k8s machine images
Fixes #
```release-note
update k8s machine images
```
=> update k8s machine images

.github/workflows/weekly-security-scan.yaml, README.md, docs/book/src/developer/release-support-guidelines.md, metadata.yaml, test/e2e/config/ibmcloud-e2e-powervs.yaml, test/e2e/config/ibmcloud-e2e-vpc.yaml
- Update Infrastructure Provider version in [metadata.yaml](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/main/metadata.yaml) and [e2e test config files](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/tree/main/test/e2e/config)
- [Update release branch versions for weekly security scan](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/main/.github/workflows/weekly-security-scan.yaml#L16)
- [Update release support data in docs](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/main/docs/book/src/developer/release-support-guidelines.md)
- [Update docs with reference to latest release](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/main/README.md#co …
=> Post v0.11.0 release housekeeping

docs/book/src/machine-images/powervs.md, scripts/ci-e2e.sh, test/e2e/config/ibmcloud-e2e-powervs.yaml
Bump PowerVS CI image to v 1.32.3
Fixes #
```release-note
Bump PowerVS CI image to v 1.32.3
```
=> Bump PowerVS CI image to v 1.32.3

templates/cluster-template-powervs-clusterclass.yaml, templates/cluster-template-powervs-clusterclass/cluster-with-kcp.yaml, templates/cluster-template-vpc-clusterclass.yaml, templates/cluster-template-vpc-clusterclass/cluster-with-kcp.yaml
Update cluster class templates with v1beta2 API changes
Fixes #2459 
```release-note
Update cluster class templates with v1beta2 API changes
```
=> Update cluster class templates with v1beta2 API changes

.github/workflows/weekly-security-scan.yaml, README.md, docs/book/src/developer/release-support-guidelines.md, metadata.yaml, test/e2e/config/ibmcloud-e2e-powervs.yaml, test/e2e/config/ibmcloud-e2e-vpc.yaml
- Post v0.12.0 release housekeeping
- Update Infrastructure Provider version in [metadata.yaml](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/main/metadata.yaml) and [e2e test config files](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/tree/main/test/e2e/config)
- [Update release branch versions for weekly security scan](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/main/.github/workflows/weekly-security-scan.yaml#L16)
- [Update release support data in docs](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/main/docs/book/src/developer/release-support-guidelines.md)
- [Update docs with reference to latest …
=> Post v0.12.0 release housekeeping

docs/book/src/introduction.md
- Add release-0-12 book link
Fixes #
```release-note
Add release-0-12 book link
```
=> Add release-0-12 book link
