kubernetes-sigs/cluster-api-provider-ibmcloud

cmd/clusterctl/configuration/ibmcloud/machines.yaml.template
cmd/manager/main.go
pkg/cloud/ibmcloud/deployer.go

This is part of #43 
`provider-component.yaml` is better to have before following up `clusterctl` fix.

clusterctl : register ibmcloud and fix machine template issue

---

cmd/clusterctl/example/ibmcloud/generate-yaml.sh
pkg/cloud/ibmcloud/deployer.go

- IBM specific ssh key name
The key is used to access IBM Cloud VM instances with `ssh -i path-to-ssh-key`. The key is generated on demands
- clean generate.sh
It does not need yq now.
It does not use TEMPLATES_PATH
Preparing dependecies should be in front of kustomizing logically.

IBM specific ssh key name and clean generate.sh

---

pkg/cloud/ibmcloud/actuators/machine/actuator.go
pkg/cloud/ibmcloud/clients/machines.go

Machine actuator API of `Exists` return `true` or `false` with no error for common check. It is error if other condition happens in API implementation.
Previously, I try to use not found case as an error. It is not convenient for this case and make API logic wrong
Fixes #91

return error for not found case makes checking existence fail

---

Makefile
config/default/manager_image_patch.yaml
config/manager/manager.yaml

as discussed in #116, we use simple name instead of full name because it is already under ibm account.

use simple image name

---

Makefile

1. the target name should better be noun 
- `build-images` -> `images`. `make images` seems better than `make build-images`. BTW, `all` target has dependecy to `images` already.
-  keep `push-images` (and push*) as is because it is more descriptive
2. add single binary image build and push
For development work, a single controller build and push is most common operation. I need it to refresh image quickly.

make independent binary image build

---

OWNERS_ALIASES

rtheis is one of the sig ibm cloud leads representing IKS.

Add rtheis

---

Gopkg.lock
pkg/cloud/ibmcloud/actuators/machine/actuator.go
pkg/cloud/ibmcloud/clients/machines.go
vendor/github.com/softlayer/softlayer-go/filter/filters.go

make code logic simple and clear. 
/cc @gyliu513 @jichenjc 
Still need to do below things in this PR before review

get vm by name instead of search in a list

---

pkg/cloud/ibmcloud/clients/machines.go

Fixes #139
It is originally for easy debug to me. Now, it should be log in debug.

lower log level for VM instance provision message

---

pkg/cloud/ibmcloud/actuators/machine/actuator.go

Fixes #165
- deleting is just a temporary phase. It does not show that the host is deleted.
- when pivot a machine, its phase is not updated
/sig ibmcloud
```release-note
```

fix phase issue

---

config/manager/manager.yaml
docs/trouble_shooting.md

- rename : `s/clusterapi-controllers/clusterapi-controller/`
There is no convention for `statefulset` to use plural names. And I checked several providers, they use "controller-manager" as name. As there is namespace name for indication in `ibmcloud-provider-system`, I think both `controller-manager` and `clusterapi-controller` are fine.
- fix doc: statefulset controller only has postfix -0 as for cluster api provider controller

Fix documents

---

cmd/clusterctl/examples/ibmcloud/machines.yaml.template

Change the default value to 4 for cpu to avoid such error occurs:
```
root@ibmcloud-master-rcgs5:/var/log# tail cloud-init-output.log
I0524 06:15:17.046374    4466 checks.go:131] validating if the service is enabled and active
I0524 06:15:17.072787    4466 checks.go:209] validating availability of port 10250
I0524 06:15:17.072863    4466 checks.go:209] validating availability of port 2379
I0524 06:15:17.072892    4466 checks.go:209] validating availability of port 2380
I0524 06:15:17.072922    4466 checks.go:254] validating the existence and emptiness of directory /var/lib/etcd
error execution phase preflight: [preflight] Some fatal errors occurred:
[ERROR NumCPU]: the number of available CPUs 1 is less than the required 2
[preflight] If you know what you are doing, you can make a check …
```

Update machine cpu to 4

---

docs/trouble_shooting.md

kind 0.3.0 cannot work with docker 18.09.6 on ubuntu
Append some steps to check if kind works with docker for trouble-shooting before user create k8s cluster on ibmcloud.
**Which issue(s) this PR fixes**:
Fixes #186 
User can find solution to fix the issue
https://github.com/kubernetes-sigs/kind/issues/567
/sig ibmcloud
No any change on images.
```release-note
NONE
```

Enhance doc of trouble-shooting for cannot create cluster by kind

---

cmd/manager/Dockerfile

Change base image to avoid security issues.
1) Tested image build.
2) Test create a cluster on SL.
3) Passed image security scan.
https://quay.io/repository/wanghh2000/cluster-api-provider-ibmcloud-controller/manifest/sha256:f22bb127d99eeab3e53741318fe0df5349e2a8cf66bc73aab895144934062f81?tab=vulnerabilities
Fixes #115 
/sig ibmcloud
No version change, and just change base image.
**Release …

Update base image to fix security issue

---

cmd/manager/main.go
pkg/cloud/ibmcloud/actuators/machine/actuator.go
pkg/cloud/ibmcloud/options/options.go

This is not the perfect solution but a better way in my thought.
The `options` package with `init()` function to register flags to controller to avoid deeply passing arguments in a framework. This is not what I like but suitable in this case.
Make `options` under `ibmcloud` because most of configurable items should for ibmcloud.
Fixes #
/sig ibmcloud
```release-note
```

add command line options for ibm cloud operation

---

config/manager/manager.yaml
pkg/cloud/ibmcloud/clients/machines.go
pkg/cloud/ibmcloud/options/options.go

Make timeout configurable if it need a long time for ibmcloud. User can update the value before creating a cluster.
```
root@gummite1:~# kubectl --kubeconfig $kubeconfig exec clusterapi-controller-0 env -n ibmcloud-provider-system
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=clusterapi-controller-0
POD_NAMESPACE=ibmcloud-provider-system
CLUSTER_API_IBMCLOUD_ACTIVE_TRANSACTIONS_TIMEOUT=446
CONTROLLER_MANAGER_SERVICE_PORT_443_TCP_PORT=443
KUBERNETES_SERVICE_PORT=443
CONTROLLER_MANAGER_SERVICE_PORT_443_TCP=tcp://10.110.232.184:443
CONTROLLER_MANAGER_SERVICE_PORT_443_TCP_ADDR=10.110.232.184
KUBERNETES_SERVICE_HOST=10.96.0.1
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_PORT_443_TCP_PROTO=tcp …
```

Make timeout configurable

---

Makefile
pkg/cloud/ibmcloud/deployer_test.go

Add unit test code for custom SSH key file
Fixes #256 
```
?       sigs.k8s.io/cluster-api-provider-ibmcloud/pkg/cloud     [no test files]
=== RUN   TestGetSSHKeyFile
--- PASS: TestGetSSHKeyFile (0.00s)
PASS
ok      sigs.k8s.io/cluster-api-provider-ibmcloud/pkg/cloud/ibmcloud    (cached)
Generating SSH key files for IBM cloud machine access.
Generating public/private rsa key pair.
Your identification has been saved in /root/.ssh/id_ibmcloud.
Your public key has been saved in /root/.ssh/id_ibmcloud.pub.
The key fingerprint is:
SHA256:Ki+jgTbHDs/W99lAMthpqK7u7nAXmn44D1li5h/6ugI …
```

Add unit test code of GO/Shell functions for custom SSH key file

---

pkg/cloud/ibmcloud/deployer_test.go

Add unit test for all functions of deployer.go and it can go through code logic of fun `GetKubeConfig`, then return "" since fake IP and ssh user name for `util.ExecCommand`.
```
ok      sigs.k8s.io/cluster-api-provider-ibmcloud/pkg/bootstrap (cached)
?       sigs.k8s.io/cluster-api-provider-ibmcloud/pkg/cloud     [no test files]
=== RUN   TestGetIP
--- PASS: TestGetIP (0.00s)
=== RUN   TestGetKubeConfig
--- PASS: TestGetKubeConfig (0.15s)
=== RUN   TestGetSSHKeyFile
--- PASS: TestGetSSHKeyFile (0.00s)
PASS
ok      sigs.k8s.io/cluster-api-provider-ibmcloud/pkg/cloud/ibmcloud    0.643s
```
Fixes …

add unit test for all functions of deployer.go

---

Makefile
cmd/clusterctl/examples/ibmcloud/provider-component/user-data/ubuntu/templates/master-user-data.sh
cmd/clusterctl/examples/ibmcloud/provider-component/user-data/ubuntu/templates/worker-user-data.sh

1. The old code hardcoded docker version. But it does not exist now. Just removed and tested fine.
2. Make file change. There is no need to check and generate before build a binary. It wastes time for waiting this.

UBUNTU_LATEST does not work

---

.travis.yml
cmd/clusterctl/Dockerfile
cmd/manager/Dockerfile

Bump dockerfiles to builder use go 1.13.8
Fixes #
```release-note
dockerFile: bump builder to use go 1.13.8
```

Proposal 🏃 dockerFile: bump builder to use go 1.13.8

---

config/crd/kustomization.yaml
templates/cluster-template.yaml

2 fixes included:
- the `--kubernetes-version` passed in during `clusterctl init` is not respecte, and the reason is because it's not properly set in the template. Added that variable to kubeadmconfig, so it can be picked up and passed in to kubeadm init
- added missing `ibmvpcmachinetemplates` to kustomize 
Fixes #306
/cc @gyliu513 @jichenjc @xunpan @wentao-zh 
```release-note
```

fix: issue#306: support provision specified kube version cluster

---

README.md

The README for this repo needs greater details for users looking to leverage the IBM CAPI Provider within an IBM Cloud VPC2 environment. I recently went through this process and the current README was insufficient. Having successfully provisioned a workload cluster in IBM Cloud VPC2, this PR contains the instructions necessary for other users to successfully accomplish that same task.
**Which issue(s) this PR fixes**
This PR fixes #317 
```release-note
NONE
```

README - add IBM Cloud VPC2 instructions

---

README.md

**What this PR does / why we need it**: This PR aims to add a simple note about the file extension `qcow2` required by the IBM Custom Image creation process.
**Special notes for your reviewer**: I'm not sure if this extension requirement is something new. I've started my tests yesterday (May 25) and got the following error while trying to use the image object from the Object Storage.
```json
{
"name": "StatusCodeError",
"statusCode": 400,
"error": {
"errors": [
{
"code": "cos_invalid_file_extension",
"message": "The uri provided contains an unsupported file extension.",
"more_info": "http://cloud.ibm.com/docs/vpc-on-classic?topic=vpc-on-classic-rias-error-messages#cos_invalid_file_extension",
"target": {
"name": "file.href", …
```

Adding a note about qcow2 extension

---

Dockerfile
Makefile
versions.mk

This PR is to allow make to build malti-arch fat manifest image
Fixes #
```release-note
NONE
```

Build multi-arch manifest image

---

.gitignore
controllers/suite_test.go
scripts/ci-test.sh

This PR provides the ability to generate JUnit XML test reports and populate the prow dashboard accordingly for the unit tests.
Fixes #328 
/cc @gyliu513 @jichenjc @xunpan @mkumatag 
```release-note
NONE
```

Support JUnit XML test report

---

Makefile

Recent changes made for generating/pushing release artifacts was missing these 2 variables and this PR will fix that.
error: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-cluster-api-provider-ibmcloud-push-images/1457712265217183744
The error introduced in https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/411
Fixes #
```release-note
```

fix the BUCKET variable

---

docs/book/src/developer/tilt.md

Adding document for deploying clusters using Tilt.
Fixes #346 
```release-note
NONE
```

Add doc for deployment using tilt

---

README.md

- Added Compatibility matrix
- Removed all the unnecessary content and mentioned the hosted doc for the references
Fixes #359 
```release-note
```

Include Compatibility matrix and update the readme

---

Makefile
config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachinetemplates.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcmachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcmachinetemplates.yaml
config/rbac/role.yaml
config/webhook/manifests.yaml
hack/tools/Makefile
hack/tools/go.mod
hack/tools/go.sum

- Use the controller-gen from hack/tools module
- Update controller-gen to the latest version available.
Fixes #
```release-note
NONE
```

use controller-gen from hack/tools

---

cloud/scope/powervs_cluster.go
cloud/scope/powervs_machine.go

This will disable the power client debug logs by default, user needs to supply `-v=5` flag to enable them.
Fixes #478 
```release-note
```

Make powervs debug log optional

---

cloud/scope/powervs_machine.go
controllers/ibmpowervsmachine_controller.go
main.go

- Added `sync-period` flag and set 10min as a default value
- Overriding the value via `RequeueAfter` in the machine controller wherever required to cut the deployment time
Fixes #510 
```release-note
NONE
```

Add sync-period flag

---

OWNERS

please see [kubernetes/community#6334](https://github.com/kubernetes/community/issues/6334)
Signed-off-by: Davanum Srinivas <davanum@gmail.com>
What type of PR is this?   
/kind cleanup
What this PR does / why we need it:
Which issue(s) this PR fixes: 
Fixes #
Special notes for your reviewer:
Does this PR introduce a user-facing change?  
```
NONE
```
Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```
```

Validate OWNERS files - remove sections about emeritus reviewers.

---

api/v1beta1/common.go
api/v1beta1/ibmpowervscluster_types.go
api/v1beta1/ibmpowervscluster_webhook.go
api/v1beta1/ibmpowervsmachine_types.go
api/v1beta1/ibmpowervsmachine_webhook.go
api/v1beta1/ibmpowervsmachinetemplate_webhook.go
config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachinetemplates.yaml
controllers/ibmpowervscluster_controller_test.go

- Fix network name and id related webhook validation checks
- Fix image name and id related webhook validation checks
Fixes #521 
```release-note
```

Fix network/image webhook validations

---

api/v1beta1/conditions_consts.go
api/v1beta1/ibmpowervsimage_types.go
api/v1beta1/types.go
cloud/scope/powervs_image.go
config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsimages.yaml
controllers/ibmpowervsimage_controller.go

Added a new condition to log the image import state properly and also include the state for the image from the import job.
Fixes #
```release-note
```

handle image import job properly

---

Makefile
scripts/ci-e2e.sh

E2E tests require kubectl as a prerequisite. Install it via existing scripts.
Fixes #
```release-note
```

Install kubectl for e2e tests

---

docs/book/src/developer/release.md

Fixes #410 
```release-note
```

Document the release process

---

controllers/ibmpowervsmachine_controller.go

Fixes #
- Fix integration of IBMPowerVSImage with MachineSpec
```release-note
```

Bugfix - Integrate IBMPowerVSImage with MachineSpec

---

cloud/scope/powervs_image.go
controllers/ibmpowervsimage_controller.go
pkg/cloud/services/powervs/service.go

- Handle a delete image flow when IBMPowerVSImage is deleted and image import job is in-progress
Fixes #548 
```release-note
```

Update delete image flow

---

hack/boskos.sh
scripts/ci-e2e.sh

Signed-off-by: Amulyam24 <amulmek1@in.ibm.com>
Adds support for using Boskos for proper resource cleanup in E2E tests.
Fixes #546 
```release-note
NONE
```

Use Boskos for proper resource cleanup

---

api/v1beta1/ibmpowervsimage_types.go
api/v1beta1/types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsimages.yaml
controllers/ibmpowervsimage_controller.go

- Add DeletePolicy to IBMPowerVSImage Spec
Fixes #542 
```release-note
```

Add DeletePolicy to IBMPowerVSImage Spec

---

cloud/scope/powervs_cluster.go
cloud/scope/powervs_image.go
cloud/scope/powervs_machine.go
pkg/cloud/services/powervs/service.go

Signed-off-by: Amulyam24 <amulmek1@in.ibm.com>
The PowerVS client would be mocked for unit tests. `gomock` expects the mocked type to be an interface, hence change the `IBMPowerVSClient` to be of type `PowerVS`.
Fixes #
```release-note
```

Change IBMPowerVSClient type for better mocking

---

README.md

This change contains:
- Add cluster-api 0.x version in the table instead of 0.1 to cover versions like 1.1, 1.2 etc..
- Removed the k8s matrix and pointing to the version published by the cluster-api project
Fixes #
```release-note
```

Update the version matrix

---

docs/book/src/getting-started.md

Improve doc by adding note for using provider tags.
Fixes #571 
```release-note
NONE
```

Add note for using provider versions

---

cloud/scope/powervs_image.go
go.mod
go.sum

Fixes #620 
```release-note
```

Handle the scope properly

---

docs/book/src/SUMMARY.md
docs/book/src/topics/powervs/creating-a-cluster.md
docs/book/src/topics/powervs/external-cloud-provider.md
hack/ccm/Dockerfile
hack/ccm/Makefile
hack/ccm/cloudbuild.yaml
templates/cluster-template-powervs-cloud-provider.yaml

This PR contains the changes to include a power vs cluster template with external cloud provider integration
Fixes #[449](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/449)
```release-note
```

Add external Power VS cloud provider support

---

hack/ccm/Makefile

Fixes #629
```release-note
NONE
```

Fix docker buildx build

---

cloud/scope/cluster.go
cloud/scope/machine.go
cloud/scope/powervs_image.go
cloud/scope/powervs_machine.go
controllers/ibmpowervscluster_controller.go
controllers/ibmpowervsimage_controller.go
controllers/ibmpowervsmachine_controller.go
controllers/ibmvpccluster_controller.go
controllers/ibmvpcmachine_controller.go
go.mod
main.go
pkg/record/doc.go
pkg/record/record.go

- Add events recorder framework
Fixes #547 
```release-note
Add events recorder framework
```

Add events recorder framework

---

cloud/scope/powervs_machine.go
config/default/manager_auth_proxy_patch.yaml
config/manager/manager.yaml
docs/book/src/developer/tilt.md
docs/book/src/getting-started.md
main.go
pkg/options/options.go

This PR contains the changes to set the ProviderID format for Power VS
Fixes #
```release-note
```

Add environmetal variable to set providerID format

---

config/manager/manager.yaml
scripts/ci-e2e.sh

Sets loglevel to 5 for allowing debug logs from controller.
Fixes #617 
```release-note
NONE
```

Add debug loglevel for E2E runs

---

api/v1beta1/conditions_consts.go
api/v1beta1/types.go
controllers/ibmpowervsmachine_controller.go

This PR handle the ERRORED state of the virtual server properly.
Fixes #
```release-note
```

Handle the ERRORED state properly

---

Makefile
hack/tools/Makefile

- Setup the prerequisites for running the unit tests
Fixes #661 
```release-note
prerequisites for running the unit tests
```

prerequisites for running the unit tests

---

hack/ccm/Dockerfile
hack/ccm/Makefile

This PR updates ccm dockerfile and makefile to remove building vpcctl binary as its been removed in latest update to powervs cloud provider.
Fixes #
```release-note
```

Update ccm dockerfile to remove building vpcctl binary

---

Dockerfile

This will update the golang version to the latest version in the Dockerfile
Fixes #
```release-note
```

Update the golang version

---

docs/book/src/topics/powervs/creating-a-cluster.md
docs/book/src/topics/powervs/external-cloud-provider.md
docs/book/src/topics/vpc/creating-a-cluster.md
templates/README.md

- Doc updates related to workload cluster creation
Fixes #663 
```release-note
- Doc updates
```

Doc updates

---

Makefile
scripts/ci-test-coverage.sh

- Add test coverage target to Makefile
Fixes #
```release-note
Add test coverage target to Makefile
```

Add test coverage target to Makefile

---

cloud/scope/powervs_cluster.go
cloud/scope/powervs_machine.go
cloud/scope/powervs_test.go
controllers/ibmpowervscluster_controller_test.go
controllers/ibmpowervsmachine_controller_test.go

Adds unit tests for PowerVS controllers.
Increases the coverage of package `controllers` from 2.8% to 26.1%
Fixes #
```release-note
```

Improve UT coverage for IBMPowerVS controllers

---

cloud/scope/powervs_image.go
cloud/scope/powervs_image_test.go
controllers/ibmpowervscluster_controller_test.go
controllers/ibmpowervsimage_controller_test.go
controllers/ibmvpccluster_controller_test.go
controllers/ibmvpcmachine_controller_test.go

Adds unit tests for PowerVS image and VPC controllers
Fixes #
```release-note
```

Improve UT coverage for controllers pkg

---

cloud/scope/common_test.go
cloud/scope/machine_test.go
cloud/scope/powervs_cluster.go
cloud/scope/powervs_image.go
cloud/scope/powervs_machine.go
cloud/scope/powervs_machine_test.go
pkg/cloud/services/powervs/service.go
pkg/endpoints/endpoints_test.go

- Minor refactoring of code to improve `cloud/scope` package coverage
- Improved `endpoints` package coverage
Fixes #
```release-note
Minor UT coverage improvements
```

Minor UT coverage improvements

---

cloudbuild.yaml

…test version
Bugfix - update gcr.io/k8s-staging-test-infra/gcb-docker-gcloud to latest version
Post updating golang, it has been observed that the post-merge prow job for pushing capi image is failing. The prow job is using image with go version 1.16.2 which is causing the issue. Updating it to new image having go version 1.18.3
Ref job log - https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-cluster-api-provider-ibmcloud-push-images/1549655520623726592
Fixes #
1. Please …

Bugfix - update gcr.io/k8s-staging-test-infra/gcb-docker-gcloud to latest version

---

api/v1beta1/ibmpowervscluster_types.go
api/v1beta1/ibmpowervsmachine_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachines.yaml

After the fix this is how the print table looks like:
```shell
$ k get ibmpowervsmachines -A
NAMESPACE   NAME                                CLUSTER         AGE    READY   STATE    HEALTH
default     ibm-powervs-1-control-plane-2w7l5   ibm-powervs-1   2d2h   true    ACTIVE   OK
default     ibm-powervs-1-md-0-fwhkc            ibm-powervs-1   2d1h   true    ACTIVE   OK
default     ibm-powervs-1-md-0-l5knj            ibm-powervs-1   2d1h   true    ACTIVE   OK
$ k get ibmpowervsmachines -A -o=wide
NAMESPACE   NAME                                CLUSTER         MACHINE                               AGE    READY   INTERNAL-IP       EXTERNAL-IP     STATE    HEALTH
default     ibm-powervs-1-control-plane-2w7l5   ibm-powervs-1 …
```

Enhance the print column for powervs resources

---

hack/boskos.sh
scripts/ci-e2e.sh

The API Key used by an e2e test is given restricted access based on the necessary operations. Using resource-group while logging into IBM Cloud account can be ignored as it would require giving additional resource-group permissions which might not be needed.
Fixes #
```release-note
```

Fix E2E job failure

---

config/manager/manager.yaml
pkg/endpoints/endpoints.go
pkg/endpoints/endpoints_test.go

- Assign default value to SERVICE_ENDPOINT to make it optional variable.
Fixes #836
```release-note
make SERVICE_ENDPOINT variable optional
```

make SERVICE_ENDPOINT variable optional

---

.golangci.yml
pkg/cloud/services/utils/accounts.go

- Enable additional linters (+13)
- Inline with list of linters used in CAPIAWS
Fixes #848 
```release-note
Enable additional linters
```

Enable additional linters

---

cloud/scope/cluster.go
controllers/ibmvpccluster_controller.go
controllers/ibmvpccluster_controller_test.go

Fixes #842 
Template which contains the user defined port for the Apiserver:
```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
labels:
cluster.x-k8s.io/cluster-name: ibm-vpc-1
name: ibm-vpc-1
namespace: default
spec:
clusterNetwork:
apiServerPort: 443
pods:
cidrBlocks:
- 192.168.0.0/16
serviceDomain: cluster.local
services:
cidrBlocks:
- 10.128.0.0/12
```
`spec->clusterNetwork->apiServerPort`
Deployed cluster:
```yaml
k cluster-info
Kubernetes control plane is running at https://8c6cb435-us-east.lb.appdomain.cloud:443
CoreDNS is running at …
```

User defined port for the control plane for vpc

---

cloud/scope/cluster.go
cloud/scope/cluster_test.go
cloud/scope/machine.go
cloud/scope/machine_test.go
controllers/ibmvpccluster_controller_test.go
controllers/ibmvpcmachine_controller.go
controllers/ibmvpcmachine_controller_test.go

- Add unit tests for VPC LB integration
- Improved refactoring and optimisation of overall UTs
Fixes #834 
```release-note
Add unit tests for VPC LB integration
```

Add unit tests for VPC LB integration

---

Makefile
scripts/ci-e2e.sh
test/e2e/config/ibmcloud-e2e-vpc.yaml

- support e2e vpc test flow
Fixes #619 
```release-note
support e2e vpc test flow
```

support e2e vpc test flow

---

hack/ccm/Makefile

To add build image targets in ccm Makefile. This is needed for presubmit job to ccm Dockerfile.
Related to https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/870

Add build image targets in ccm Makefile

---

.dockerignore

- This PR will add a `.dockerignore` file. We need it to reduce the docker image build size and make the build faster
**Which issue(s) this PR fixes** 
Fixes #939

chore: Added `.dockerignore`

---

cloud/scope/powervs_image.go
controllers/ibmpowervsimage_controller.go

This change removes the need of cluster reference while deleting the ibmpowervsimage resources
Fixes #
```release-note
```

Changes to support ibmpowervs image deletion without cluster reference

---

controllers/ibmpowervscluster_controller.go

This PR adds the filter to IBMPowerVSCluster reosurce to avoid reconciliation if the resource has the externally managed annotation(cluster.x-k8s.io/managed-by) set. 
Enhancement: https://github.com/kubernetes-sigs/cluster-api/blob/10d89ceca938e4d3d94a1d1c2b60515bcdf39829/docs/proposals/20210203-externally-managed-cluster-infrastructure.md
Fixes #
```release-note
```

Add externally managed annotations to IBMPowerVSCluster resource

---

go.mod
go.sum
hack/tools/go.mod
hack/tools/go.sum
test/e2e/config/ibmcloud-e2e-powervs.yaml
test/e2e/config/ibmcloud-e2e-vpc.yaml

- Update cluster-api to v1.2.5
Fixes #951 
```release-note
Update cluster-api to v1.2.5
```

Update cluster-api to v1.2.5

---

docs/book/src/SUMMARY.md
docs/book/src/developer/tilt.md
docs/book/src/getting-started.md
docs/book/src/topics/powervs/clusterclass-cluster.md
docs/book/src/topics/powervs/index.md
templates/cluster-template-simple-powervs-clusterclass.yaml

ClusterClass support for Power VS was added with the [PR](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/967): , This PR adds the documentation on how to create cluster using ClusterClass
Fixes #
```release-note
Added documentation on how to use ClusterClass template to create Power VS cluster
```

Added documentaion for usage of ClusterClass to create Power VS cluster

---

cloud/scope/machine.go
cloud/scope/powervs_machine.go
config/manager/manager.yaml
controllers/ibmvpcmachine_controller.go
docs/book/src/SUMMARY.md
docs/book/src/developer/tilt.md
docs/book/src/getting-started.md
docs/book/src/topics/powervs/external-cloud-provider.md
docs/book/src/topics/vpc/load-balancer.md
main.go
pkg/cloud/services/utils/accounts.go
pkg/options/options.go
templates/cluster-template-load-balancer.yaml
templates/cluster-template-powervs-cloud-provider.yaml

This PR adds the support to use external cloud controller for VPC cluster, Major changes included are
1. Made changes to update the provider id format for VPC machines as per the [ibmcloud ccm](https://github.com/Karthik-K-N/cloud-provider-powervs/blob/ef98e354790dd988eaa47b81416b412dd64afeab/ibm/ibm_instances.go#L240)
2. Added command line flag named provider-id-format to allow user to select the provider id format. For ccm  support it should be set to v2.
3. Added template to create cluster with external cloud controller.
4. Added necessary documentation to configure  external cloud controller.
With this support now users will be able to create a service of type LoadBalancer in workload clusters.
Previous PR to add external cloud provider support …

Add external cloud provider support for VPC

---

hack/boskos.sh
scripts/ci-e2e.sh

Adds changes for running VPC e2e tests with Boskos.
Fixes #
```release-note
Integrate running VPC e2e tests with Boskos
```

Integrate running VPC e2e tests with Boskos

---

cloud/scope/cluster.go
cloud/scope/cluster_test.go
controllers/ibmvpccluster_controller_test.go

This PR will list the subnets before deleting to ensure that there is a subnet exist otherwise it will return the delete subnet flow successfully.
Fixes #1031 
```release-note
```

Fix the delete subnet flow

---

cloudbuild.yaml
hack/ccm/cloudbuild.yaml

- Migrate away from google.com gcp project k8s-testimages
- also update `gcb-docker-gcloud` to a newer image
Related to https://github.com/kubernetes/k8s.io/issues/1523
/assign @ameukam @mkumatag
Fixes #
```release-note
NONE
```

Migrate away from google.com gcp project k8s-testimages

---

Makefile
scripts/ci-e2e.sh
test/e2e/config/ibmcloud-e2e-powervs.yaml

- Introduce ginkgo timeout
Fixes #
```release-note
Introduce ginkgo timeout
```

fix PVS e2e - introduce ginkgo timeout

---

cmd/capibmadm/clients/powervs/client.go
cmd/capibmadm/cmd/powervs/powervs.go
cmd/capibmadm/cmd/root.go
cmd/capibmadm/cmd/vpc/vpc.go
cmd/capibmadm/options/options.go
cmd/capibmadm/printer/printer.go

Add common flags needed for cli.
Fixes #
```release-note
```

Add common flags for capibmadm cli

---

cmd/capibmadm/cmd/powervs/port/list.go
cmd/capibmadm/cmd/powervs/port/port.go
cmd/capibmadm/cmd/powervs/port/type.go
cmd/capibmadm/cmd/powervs/powervs.go
docs/book/src/SUMMARY.md
docs/book/src/topics/capibmadm/powervs/index.md
docs/book/src/topics/capibmadm/powervs/port.md

This PR is for listing ports from PowerVC
```
$ ./capibmadm powervs port list --service-instance-id "b9db6009-30fc-4718-98cb-16ba6fd37b82"  --zone mon01 --network rdr-acm-spoke2-411-mon01-pub-net
Listing PowerVS ports service-instance-id="b9db6009-30fc-4718-98cb-16ba6fd37b82" network="rdr-acm-spoke2-411-mon01-pub-net"
DESCRIPTION   EXTERNALIP      IPADDRESS        MACADDRESS          PORTID                                 STATUS
169.54.110.91   192.168.164.91   fa:d4:c3:31:24:20   19712105-d5be-4e97-9fc1-d9f49300ddf9   ACTIVE
```
Fixes #
/area …

Ports list command implementation - PowerVS

---

cmd/capibmadm/cmd/powervs/key/create.go
cmd/capibmadm/cmd/powervs/key/delete.go
cmd/capibmadm/cmd/powervs/key/key.go
cmd/capibmadm/cmd/powervs/powervs.go
docs/book/src/SUMMARY.md
docs/book/src/topics/capibmadm/powervs/index.md
docs/book/src/topics/capibmadm/powervs/key.md
go.mod

The PR contains the changes to support creation and deletion of ssh-keys in the powervs environment using the capibmadm tool.
The supporting documentation has also been updated.
```
kishenv@Kishens-MacBook-Pro capibmadm % ./capibmadm powervs key create --name capiadm-sshkey --key "ssh-rsa AAAAB3NzaC...(redacted)"  --zone osa21 --service-instance-id 82cac694-b9d7-45de-bab4-XXXXXXXXXXXX
Creating ssh key...
Successfully created the ssh key. name="capiadm-sshkey"
kishenv@Kishens-MacBook-Pro capibmadm % ./capibmadm powervs key delete --name capiadm-sshkey --zone osa21 --service-instance-id 82cac694-b9d7-45de-bab4-XXXXXXXXXXXX
Deleting ssh key...
Successfully deleted the ssh key. name="capiadm-sshkey"
```
**Which issue(s) this PR fixes** *(optional, in …

Support to create and delete ssh-keys in the PowerVS environment.

---

cmd/capibmadm/cmd/powervs/port/delete.go
cmd/capibmadm/cmd/powervs/port/port.go
docs/book/src/topics/capibmadm/powervs/index.md
docs/book/src/topics/capibmadm/powervs/port.md

**What this PR does / why we need it:**
To add the capibmadm port delete command
Ref https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/main/docs/proposal/20230113-capibm-cli-tool.md#7-capibmadm-powervs-port-delete

Added Port Delete command to capibmadm

---

cmd/capibmadm/cmd/powervs/port/create.go
cmd/capibmadm/cmd/powervs/port/port.go
docs/book/src/topics/capibmadm/powervs/index.md
docs/book/src/topics/capibmadm/powervs/port.md

In this PR, a CLI command to create network port is added
**Create port**
```release-note
% ./capibmadm powervs port create --network test-subnet --ip-address 192.168.100.34 --description port-desc --service-instance-id aea0ef52-dbb2-4274-87db-ca1fa85381a9 --zone osa21
Creating Port  Network ID/Name="test-subnet" IP Address="192.168.100.34" Description="port-desc" service-instance-id="aea0ef52-dbb2-4274-87db-ca1fa85381a9" zone="osa21"
Successfully created a port portID="5cb78d44-2fe7-4924-a643-9124a92b1b87"
DESCRIPTION   EXTERNAL IP   IP ADDRESS       MAC ADDRESS         PORT ID                                STATUS
port-desc                   192.168.100.34   fa:16:3e:4a:66:20   04e011ab-298b-4d2e-9626-ae893d51fc89   DOWN
```
**Which issue(s) this …

Add support for port create command

---

Makefile

Currently the images are created only for amd64 and ppc64le, adding support for arm64 also with this PR
Fixes #1112 
```release-note
```

Add support for linux/arm64 images

---

cmd/capibmadm/cmd/vpc/key/key.go
cmd/capibmadm/cmd/vpc/key/list.go
cmd/capibmadm/cmd/vpc/key/type.go
cmd/capibmadm/cmd/vpc/vpc.go
cmd/capibmadm/printer/printer.go
docs/book/src/SUMMARY.md
docs/book/src/topics/capibmadm/vpc/index.md
docs/book/src/topics/capibmadm/vpc/key.md

Signed-off-by: Punith Kenchappa <pkenchap@in.ibm.com>
This is for listing the key from the VPC. 
**O/P of this command - vpc key list --region jp-osa**
```
punithkenchappa@Puniths-MacBook-Pro-2 cluster-api-provider-ibmcloud % ./capibmadm vpc key list --region jp-osa
ID                                          NAME         TYPE   CREATED AT                 LENGTH   FINGERPRINT                                          RESOURCE GROUP
r034-5b5d022b-220e-4525-b6ef-274d41de7065   dhar-ssh     rsa    2022-06-23T07:06:45.000Z   4096     SHA256:JSp4g1DXZBr3rw+dIX1eIwCjl3/hNJrgcWqPlHv0QNg   ibm-hypershift-dev
r034-705a00a0-8eca-43a9-8014-9dfa7fbf8ab3   amulya-key   rsa    2022-08-29T11:11:57.000Z   4096     SHA256:E7RraXBL67IW22z44M0XbFc/hHvS2rqM1d/l4+U7Udw …
```

vpc key list command

---

hack/kind-network-fix.sh
scripts/ci-e2e.sh

- Fix to set desired MTU value for VPC e2e runs
Fixes #1058 
```release-note
Fix to set desired MTU value for VPC e2e runs
```

VPC e2e mtu fix

---

cmd/capibmadm/cmd/powervs/image/image.go
cmd/capibmadm/cmd/powervs/image/list.go
cmd/capibmadm/cmd/powervs/image/type.go
cmd/capibmadm/cmd/powervs/powervs.go
docs/book/src/SUMMARY.md
docs/book/src/topics/capibmadm/powervs/image.md
docs/book/src/topics/capibmadm/powervs/index.md

In this PR, a CLI command to list image  is added
```
% ./capibmadm powervs image list --service-instance-id 5e1d357c-7603-42a9-b4c1-fe3772bdfa0c --zone lon04
Listing PowerVS images service-instance-id="5e1d357c-7603-42a9-b4c1-fe3772bdfa0c"
ID                                     NAME               STATE    DESCRIPTION   STORAGE POOL    STORAGE TYPE   CREATION DATE              LAST UPDATE DATE           ARCH    CONTAINER FORMAT   DISK FORMAT   ENDIANNESS      HYPERVISOR TYPE    OS     IMAGE TYPE
06ff0390-22e1-41fe-9324-3d637bcdb6f1   CentOS-Stream-8    active                 Tier3-Flash-1   tier3          2023-02-16T15:00:00.000Z   2023-02-16T15:01:31.000Z   ppc64   bare               raw           little-endian   phyp               rhel   stock …
```

Add support for powervs image list command

---

Dockerfile
hack/ccm/Dockerfile

- Uplift golang to 1.19.6 due to https://osv.dev/vulnerability/GO-2023-1571
Fixes #
```release-note
update golang to 1.19.6
```

update golang to 1.19.6

---

cmd/capibmadm/cmd/vpc/key/create.go
cmd/capibmadm/cmd/vpc/key/delete.go
cmd/capibmadm/cmd/vpc/key/key.go
docs/book/src/topics/capibmadm/vpc/index.md
docs/book/src/topics/capibmadm/vpc/key.md

This is for creating and deleting key from VPC.
```
%./capibmadm vpc key create --name test-key --key-path /Users/madhankumar/.ssh/id_rsa.pub --region eu-de 
VPC Key created successfully, key-name="test-key"
```
```
% ./capibmadm vpc key create  --name test-key --public-key "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDHeTZS7Pxr/43AG1Z0rVktiisut+XTqODsZMBFwJX3AJUmp4K21GzOYaBYreAIAZht36I7Qw8Kv5QtqMDcZl00dkQZBHR4Gs7fQUpjZh5z6yDSm2v5SjUf7POk3kixEbyUuE1o0Hik0acaEk/18r09FHuelSsB2UvaBDjbF/1EMzrgHJ8LgnH9Md+Y/I6fb4NE3Jryrs20rC5pTxCkzX2K7NYo1oduv9pkGA2tAdukCFPgX0HjXdYP1h54MJxWU/EtMgjz85HjrWH0NYrQEV+uyh1RiBeDKRzBtqqXguXIomZhB2k0WdMPSNM5G/tkXXCM1aO1ZgCzfrn1mP1xp+gzBSjTJi5oX2KPsffP5oyTd09XRWjsjcbAUZEYbcRi8dV3CwtGB8vPFqWtzoE0NUkGTe+e+y81sEPbbikUt9PM+8MQmVDzSEfxYFVem8CJ …
```

VPC key create and delete operations added

---

Makefile
docs/book/src/developer/release.md

Replace k8s.gcr.io references with registry.k8s.io
Fixes #
```release-note
```

Replace k8s.gcr.io references with registry.k8s.io

---

cmd/capibmadm/cmd/powervs/network/create.go
cmd/capibmadm/cmd/powervs/network/delete.go
cmd/capibmadm/cmd/powervs/network/list.go
cmd/capibmadm/cmd/powervs/network/network.go
docs/book/src/topics/capibmadm/powervs/index.md
docs/book/src/topics/capibmadm/powervs/network.md

Add support for following commands:
1. powervs network create
2. powervs network delete
Fixes #
```release-note
Add powervs network create and delete commands.
```

Add powervs network create and delete cmd

---

cmd/capibmadm/options/options.go

Add shorthand "o" for output flag in cmd. This is just a minor accessibility enhancement.
Fixes #
```release-note
```

add shorthand for output flag in cmd

---

cloud/scope/cluster.go
cloud/scope/machine.go
controllers/ibmvpcmachine_controller.go
controllers/ibmvpcmachine_controller_test.go

- Fix inbound rule to allow only APIServerPort
Fixes #964 
```release-note
Fix inbound rule to allow only APIServerPort
```

Fix inbound rule to allow only APIServerPort

---

go.mod
go.sum
hack/tools/go.mod
hack/tools/go.sum
test/e2e/config/ibmcloud-e2e-powervs.yaml
test/e2e/config/ibmcloud-e2e-vpc.yaml

Updates cluster-api to v1.4.0
Fixes #1175
```release-note
```

Update cluster-api to v1.4.0

---

cloudbuild.yaml

- Enable DOCKER_BUILDKIT to fix `post-cluster-api-provider-ibmcloud-push-images` failure
Fixes #1187 
```release-note
Enable DOCKER_BUILDKIT
```

Enable DOCKER_BUILDKIT

---

scripts/ci-e2e.sh

Add DOCKER_BUILDKIT var to fix E2E tests
Fixes #
```release-note
This PR adds DOCKER_BUILDKIT var to fix E2E tests
```

Add DOCKER_BUILDKIT var to fix E2E tests

---

cloudbuild.yaml
hack/init-buildx.sh

- Fix gcloud auth required for image push
Fixes #
```release-note
Fix gcloud auth required for image push
```

Fix gcloud auth required for image push

---

cmd/capibmadm/cmd/powervs/image/import.go
cmd/capibmadm/cmd/powervs/image/list.go
cmd/capibmadm/cmd/powervs/key/create.go
cmd/capibmadm/cmd/powervs/key/delete.go
cmd/capibmadm/cmd/powervs/key/list.go
cmd/capibmadm/cmd/powervs/network/create.go
cmd/capibmadm/cmd/powervs/network/delete.go
cmd/capibmadm/cmd/powervs/network/list.go
cmd/capibmadm/cmd/powervs/port/create.go
cmd/capibmadm/cmd/powervs/port/delete.go
cmd/capibmadm/cmd/powervs/port/list.go
cmd/capibmadm/cmd/vpc/image/list.go
cmd/capibmadm/cmd/vpc/key/create.go
cmd/capibmadm/cmd/vpc/key/list.go
cmd/capibmadm/utils/utils.go

A user needs additional access for using capibmadm which internally uses GetAPIKeyDetails() for fetching the account ID. It is better to switch to the traditional approach for fetching it.
Fixes #1243 
```release-note
modify capibmadm to not use GetAPIKeyDetails to fetch the account ID
```

Modify capibmadm to not use GetAPIKeyDetails to fetch the account ID

---

pkg/record/record_test.go

Add unit test for `pkg/record/record.go`.
Fixes #1198 

Add unit test for record.go

---

api/v1beta2/conditions_consts.go
cloud/scope/powervs_machine.go
cloud/scope/powervs_machine_test.go
controllers/ibmpowervsmachine_controller.go

This PR will fix the error: "server name already exist"
As observed once the Post request to create a instance is sent, the instance obj returned is NIL and takes time to get updated due to delay in PowerVS response. This results in parallel reconciliation being triggered by changes in machine obj to resend the post request again resulting in conflict and error "server name already exist"
The fix would ensure we mark the instance state as unknown when obj returned is NIL post the create instance request is sent and check for the same conditions before sending duplicate post requests.
- fix machine reconciliation bug
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) …

fix machine reconciliation bug

---

go.mod
go.sum
hack/tools/go.mod
hack/tools/go.sum
test/e2e/config/ibmcloud-e2e-powervs.yaml
test/e2e/config/ibmcloud-e2e-vpc.yaml

- Update cluster-api to v1.4.5
Fixes #
```release-note
Update cluster-api to v1.4.5
```

[release-0.5] Update cluster-api to v1.4.5

---

hack/tools/Makefile

- fix build tags
Fixes #1316 
```release-note
fix build tags
```

fix build tags

---

docs/book/src/getting-started.md

This PR refactors the doc with a better structure.
Fixes #1152 
```release-note
Refactor the getting started guide
```

Refactor the getting started guide

---

docs/book/src/getting-started.md

- Refactor the getting started guide
Fixes #
```release-note
Refactor the getting started guide
```

[release-0.4] Refactor the getting started guide

---

docs/book/src/developer/dependencies.md

- Restructure dependency page for better readability
Fixes #
```release-note
Restructure dependency page for better readability
```

Restructure dependency page for better readability

---

scripts/ci-e2e.sh

- Enable retry of ibmcloud login command to avoid timeout failure
- Should avoid/reduce possibility of e2e Job failure as result of 3rd sub-issue of #1353
Fixes #
```release-note
Enable retry of ibmcloud login command to avoid timeout failure
```

Enable retry of ibmcloud login command to avoid timeout failure

---

scripts/ci-e2e.sh

This is a fix for a change made in [PR-1351](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/1351). BOSKOS_REGION is set later in the main function, hence use it only if it exists.
Fixes #
```release-note
Set REGION var only if BOSKOS_REGION is not nil
```

Set REGION var only if BOSKOS_REGION is not nil

---

test/e2e/config/ibmcloud-e2e-powervs.yaml
test/e2e/config/ibmcloud-e2e-vpc.yaml
test/e2e/e2e_test.go
test/e2e/suite_test.go

- Fix e2e hostname length
Error observed in e2e
```
ubelet_pods.go:414] "Hostname for pod was too long, truncated it" podName="kube-controller-manager-capi-ibmcloud-e2e-kth5c9-control-plane-p8lh9" hostnameMaxLen=63 truncatedHostname="kube-controller-manager-capi-ib>
```
Fixes #
```release-note
Fix e2e hostname length
```

Fix e2e hostname length

---

controllers/ibmpowervscluster_controller.go
controllers/ibmpowervsimage_controller.go
controllers/ibmpowervsmachine_controller.go
controllers/ibmvpccluster_controller.go
controllers/ibmvpcmachine_controller.go

- fix panic error when scope obj is not yet initialized
Fixes #1396 
```release-note
fix panic error when scope obj is not yet initialized
```

fix panic error when scope obj is not yet initialized

---

CONTRIBUTING.md

- Update doc for release and support information
Fixes #1394 
```release-note
Update doc for release and support information
```

Update doc for release and support information

---

metadata.yaml

this can trip up parsers that read the metadata file.
Fixes #
```release-note
fix: remove trailing whitespace from metadata.yaml
```

fix: remove trailing whitespace from metadata.yaml

---

README.md
docs/book/src/developer/tilt.md
docs/book/src/getting-started.md
docs/book/src/topics/powervs/clusterclass-cluster.md
docs/book/src/topics/powervs/external-cloud-provider.md

This PR contains the changes to point to the correct usage of PROVIDER_ID_FORMAT in the .md files of the CAPI book, updated references to keep documents inline with the intended usage.
Also contains a change in table's format and alignment, to adapt to a smaller space.
**Which issue(s) this PR fixes**
Fixes #1471 

PROVIDER_ID_FORMAT references replacement.

---

docs/book/src/SUMMARY.md
docs/book/src/developer/e2e.md

Add documentation for E2E testing
Fixes #1291 
```release-note
Add documentation for E2E testing
```

Add documentation for E2E testing

---

controllers/ibmpowervscluster_controller.go
controllers/ibmpowervsimage_controller.go
controllers/ibmpowervsimage_controller_test.go
controllers/ibmpowervsmachine_controller.go
controllers/ibmpowervsmachine_controller_test.go
controllers/ibmvpccluster_controller.go
controllers/ibmvpcmachine_controller.go
controllers/ibmvpcmachine_controller_test.go

This PR fixes following things:
- `controllerutil.AddFinalizer` already contains the logic for checking existing finilizer, hence the explicit check is removed
- Forcing the reconcile when the Finalizer gets add so that we don't leave behind any associated resources when delete triggers before the finalizer get added.
Fixes #1260 
```release-note
```

Fix the finalizer code

---

scripts/ci-e2e.sh

- Update e2e tooling/image bits
Fixes #
```release-note
Update e2e tooling/image bits
```

[release-0.5] Update e2e tooling/image bits

---

docs/book/src/SUMMARY.md
docs/book/src/developer/index.md
docs/book/src/developer/release-support-guidelines.md

This PR adds the support and release content to CAPIBM book doc.
Fixes #[1498](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/1498)
```release-note
Add support and release content to CAPIBM book doc
```

Add support and release content to CAPIBM book doc

---

Dockerfile
Makefile
hack/ccm/Dockerfile

- Bump golang to v1.20.12
Fixes #
```release-note
Bump golang to v1.20.12
```

[release-0.5] Bump golang to v1.20.12

---

scripts/ci-e2e.sh
test/e2e/config/ibmcloud-e2e-powervs.yaml
test/e2e/config/ibmcloud-e2e-vpc.yaml

- Bump capibm images to k8s 1.28.x for e2e flow
Fixes #
```release-note
Bump capibm images to k8s 1.28.x for e2e flow
```

Bump capibm images to k8s 1.28.x for e2e flow

---

hack/ensure-kubectl.sh

In the latest release of k8s `--short` is been removed, hence this needs to be removed.
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/1552
```release-note
```

Remove deprecated --short flag

---

api/v1beta1/zz_generated.conversion.go
api/v1beta2/ibmpowervscluster_types.go
api/v1beta2/ibmvpccluster_types.go
api/v1beta2/zz_generated.deepcopy.go
config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclusters.yaml

Couple of fields were missed during earlier PR, Updating it here.
Fixes #
```release-note
```

Update api specs

---

scripts/ci-e2e.sh

With the power-iaas plugin version update to 1.0.0, replace service-instance references with workspace. This PR fixes the below error.
```
Plug-in 'power-iaas 1.0.0' was successfully installed into /root/.bluemix/plugins/power-iaas. Use 'ibmcloud plugin show power-iaas' to show its details.
++ jq -r '.[].crn'
++ ibmcloud resource service-instance e7207381-53be-4a6a-b2c1-127580e97466 --output json
+ CRN=crn:v1:bluemix:public:power-iaas:syd04:a/7cfbd5381a434af7a09289e795840d4e:e7207381-53be-4a6a-b2c1-127580e97466::
+ ibmcloud pi service-target crn:v1:bluemix:public:power-iaas:syd04:a/7cfbd5381a434af7a09289e795840d4e:e7207381-53be-4a6a-b2c1-127580e97466::
Error: unknown command "service-target" for "pi"
Run 'pi --help' for usage.
```
**Which issue(s) …

Replace service with worskpace after power-iaas plugin update

---

docs/book/src/topics/capibmadm/index.md
docs/book/src/topics/powervs/prerequisites.md

In this PR, reference of `pvsadm image import` are replaced with the new CLI command to import images - `powervs image import`
Fixes #
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/1583
NO
```release-note
```

Replaced pvsadm image import reference with capibmadm powervs image import

---

docs/proposal/20231109-powervs-infra-creation.md

Update api specs as per new changes

---

docs/proposal/20231109-powervs-infra-creation.md

Update api specs and comments.

---

api/v1beta2/ibmpowervscluster_webhook.go
cloud/scope/powervs_machine.go

Fixes #https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/1651
```release-note
```

Support service instance id in ibmpowervsmachine reconcilation

---

api/v1beta2/ibmpowervscluster_types.go
api/v1beta2/ibmvpccluster_types.go
cloud/scope/powervs_cluster.go
config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclustertemplates.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcclustertemplates.yaml

Fix the bug where the user provided values for private/public loadbalancer was ignored.
Fixes #
```release-note
```

Configure private or public loadbalancer

---

api/v1beta2/ibmvpccluster_types.go
api/v1beta2/zz_generated.deepcopy.go
cloud/scope/powervs_cluster.go
cloud/scope/powervs_machine.go

Since Public is boolean variable , once we set it to false to create a private loadbalancer as false is unset value of boolean variable and using kubebuilder tag we are setting it default to true, so its making it not possible to create a private loadabalancer.
Now changing data type to boolean pointer so we can differentiate between unset value and false value.
Fixes #
```release-note
```

Update loadbalancer spec to configure private loadbalncer

---

api/v1beta2/ibmpowervscluster_webhook.go
cloud/scope/powervs_cluster.go
cloud/scope/powervs_image.go
cloud/scope/powervs_machine.go
docs/book/src/getting-started.md
pkg/cloud/services/cos/service.go
pkg/cloud/services/resourcecontroller/service.go
pkg/cloud/services/transitgateway/service.go
pkg/endpoints/endpoints.go
pkg/endpoints/endpoints_test.go

Adds support to override service endpoints for cos, transitgateway, resourcecontroller, powervs.
Fixes #https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/1646
```release-note
Add support to override service endpoints.
```

Add support to override service endpoints

---

controllers/ibmpowervscluster_controller.go
controllers/ibmpowervscluster_controller_test.go
main.go

Fixes #1681
```release-note
```

Use uncached client

---

api/v1beta2/ibmpowervscluster_webhook.go
api/v1beta2/types.go
cloud/scope/powervs_cluster.go
cloud/scope/powervs_machine.go
controllers/ibmpowervscluster_controller.go

- Fix cos flow
Fixes #
```release-note
Fix cos flow
```

Fix cos flow

---

api/v1beta2/ibmpowervscluster_webhook.go

Remove the check for COS instance values while creating IBMPowerVSCluster as we take care of it internally while reconciling and create the resources if ignition is set.
Fixes #
```release-note
Remove COS instance spec check in webhook
```

Remove COS instance spec check in webhook

---

controllers/ibmpowervscluster_controller.go
controllers/ibmpowervscluster_controller_test.go
main.go

Explicitly sets the GVK for IBMPowerVSCluster, Since we are excluding IBMPowerVSCluster object from cache, When we retrive the object we [wont get TypeMeta associated](https://github.com/kubernetes/kubernetes/issues/80609) with it because of it we are not able to filter out the childrens of the object , IBMPowerVSImage is one of them so it fails to delete it.
Also reverted the uncached client commit and updated the manager to exclude specifically IBMPowerVSCluster from cache.
Fixes #1690
1. Please confirm that if this PR changes any …

Explicitly set GVK for IBMPoweVSCluster resource

---

api/v1beta2/types.go
cloud/scope/powervs_cluster.go
controllers/ibmpowervscluster_controller.go

This PR adds changes to avoid returning error while infra resource creation and deletion is in progress and manages it via requeuing for each resource after a certain period of time by fetching its current state.
Fixes #1647 
```release-note
Avoid returning error when resource creation and deletion is in progress
```

Avoid returning error when resource creation and deletion is in progress

---

hack/boskos.sh
hack/kind-network-fix.sh

- Fix security exposure
Note - This PR should avoid printing any sensitive information as part of logs (even when debug mode is enabled)
Fixes #
```release-note
Fix security exposure
```

Fix security exposure

---

cloud/scope/powervs_machine.go
main.go

When the workspace has multiple DHCP servers and one of them is in building, The network id will be nil
Example
```
[{"id":"35bee472-f363-4921-b116-7d98b1711899","network":{"id":null,"name":null},"status":"BUILD"},{"id":"0303c8e5-2805-4afd-bf4d-bfbaad93056f","network":{"id":"8bab36e6-c655-46fa-bbc7-c7a7cfadc937","name":"DHCPSERVERcapi-uncache-karthik_Private"},"status":"ACTIVE"}]
```
This PR adds a check against network id before dereferencing it.
Fixes #
1. Please confirm that if this PR changes any image versions, then that's the …

Validate DHCP network id 

---

api/v1beta2/types.go

Some of the kubebuilder validation logic was written inversely and needs to be fixed so validation is done correctly.
**What this PR does / why we need it**: Some kubebuilder validation is written inversely, or is incorrect, causing issues with valid definitions.
Fixes #
```release-note
Fix kubebuiler validation for new SecurityGroup related resources
```

Fix kubebuilder validation for SecurityGroup resources

---

Makefile
hack/ccm/Makefile

- bump golang to v1.21.9
- fix trivy reported vulnerabilities 
Fixes #
```release-note
bump golang to v1.21.9
```

bump golang to v1.21.9

---

cloud/scope/powervs_cluster.go

Currently the loadbalancer reconcilation fails when the user provides the subnet id. This PR tries to fix it.
```
E0415 15:07:02.894010  185735 controller.go:329] "Reconciler error" err="error subnet required for load balancer creation" controller="ibmpowervscluster" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="IBMPowerVSCluster" IBMPowerVSCluster="openshift-cluster-api-guests/rdr-mjturek-capi-mad-rvqk9" namespace="openshift-cluster-api-guests" name="rdr-mjturek-capi-mad-rvqk9" reconcileID="80ca122b-0b9b-4f95-bcc1-34c06faf686e"
```
IBMPowerVSCluster spec
```
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: IBMPowerVSCluster
metadata:
annotations:
powervs.cluster.x-k8s.io/create-infra: "true"
creationTimestamp: null …
```

Use user provided vpc subnetid

---

cloud/scope/powervs_cluster.go
pkg/cloud/services/resourcemanager/doc.go
pkg/cloud/services/resourcemanager/resourcemanager.go
pkg/cloud/services/resourcemanager/service.go
pkg/endpoints/endpoints.go

This PR refactors to user interface for resource manager related operations, This will allow help us while implementing unit tests.
Also allows users to override the resource manager endpoint URL.
Fixes #https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/1731
```release-note
Allow users to override the resource manager endpoint URL
```

Refactor resource manager to use interface and override resource manager endpoint URL

---

cloud/scope/powervs_cluster.go
cloud/scope/types.go

Add custom type for resource not found error
Fixes #
```release-note
Add custom type for resource not found error
```

Add custom type for resource not found error

---

.github/dependabot.yml

Currently, dependent module CAPI 1.7 and k8s 1.29 are tagged to go version 1.21.  For updating the package `github.com/IBM/networking-go-sdk`, we need to update the job image to support go 1.22. Until we officially move to go version 1.22, ignore updating the package.
Fixes #
```release-note
Ignore updating github.com/IBM/networking-go-sdk until we move to go 1.22
```

Ignore updating github.com/IBM/networking-go-sdk until we move to go 1.22

---

cloud/scope/powervs_cluster.go

Verify if ID is present in Status before returning it to avoid nil pointer issue
Fixes #
```release-note
Verify if ID is present in Status before returning it to avoid nil pointer issue
```

Verify if ID is present before using it

---

docs/book/src/developer/build-images.md

Update PowerVS image builder document

---

controllers/ibmpowervscluster_controller.go
controllers/ibmvpccluster_controller.go
main.go

This PR does two things
1. Rearranging main.go
Rearranged functions in main.go for better readability purpose
2. Use same context for manager and controller
Currently there is new context created and used under each controller, Instead of that now reusing the manager's context for each controller, This will help in using same log format accross each controller as we use log.FromContext() in each controllers.
Fixes #
**Release …

Rearrange main.go and use same context for manager and controller

---

api/v1beta2/types.go
api/v1beta2/zz_generated.deepcopy.go

Update the types for PortRange fields and for ICMP fields in the Security Groups, to make setting and checking easier.
**What this PR does / why we need it**: Convert certain fields to types more in line with API fields.
Fixes #
```release-note
Converted PortRange and ICMP fields for Security Group Rules to be more in line with API
```

Update PortRange and ICMP types for Security Groups

---

cloud/scope/cluster.go
cloud/scope/cluster_test.go
cloud/scope/machine.go
cloud/scope/machine_test.go
cloud/scope/powervs_cluster.go
cloud/scope/powervs_image.go
cloud/scope/powervs_image_test.go
cloud/scope/powervs_machine.go
cloud/scope/powervs_machine_test.go
controllers/ibmpowervscluster_controller_test.go
controllers/ibmpowervsimage_controller_test.go
controllers/ibmpowervsmachine_controller_test.go
controllers/ibmvpccluster_controller_test.go
controllers/ibmvpcmachine_controller_test.go
main.go
test/helpers/envtest.go

Currently we are using textlogger, using which we are not able to see any V level logs, For example. log.V(3).Info("hello").
This PR contains the change which uses klog.Background() instead of text logger.
Fixes #
```release-note
Switch to kloger instead of textloger
```

User klog.Background() instead of textlogger

---

cloud/scope/powervs_cluster.go
pkg/cloud/services/powervs/mock/powervs_generated.go
pkg/cloud/services/powervs/powervs.go
pkg/cloud/services/powervs/service.go

Currently IsPowerVSZoneSupportsPER() uses a get call directly to fetch datacenter information, this might be a problem to mock when we have to add unit tests, hence refactoring the code to use interface.
Fixes #1774

Refactor IsPowerVSZoneSupportsPER() code to use interface

---

docs/book/src/machine-images/vpc.md
scripts/ci-e2e.sh
test/e2e/config/ibmcloud-e2e-vpc.yaml

Bump k8s version to 1.29 in e2e for VPC
Fixes # part of #1782
```release-note
Bump k8s version to 1.29 in e2e for VPC
```

Bump k8s version to 1.29 in e2e for VPC

---

cloud/scope/machine.go

When instance creation fails, do not proceed with deleting VPC load balancer bool member as It doesn't exist.
Fixes #1784 
```release-note
skip load balancer pool member deletion if instance creation fails
```

skip load balancer pool member deletion if instance creation fails

---

cloud/scope/powervs_cluster.go

This PR addresses the following
- When a PowerVS service instance creation fails, deletion of it will never go through as fetching DHCP servers will give an error as service instance doesn't exist. Add a check to verify it before proceeding for deletion
```
"Reconciler error" err="failed to delete Power VS service instance: failed to fetch networks in the PowerVS service instance: failed to Get all DHCP servers: [GET /pcloud/v1/cloud-instances/{cloud_instance_id}/services/dhcp][403] pcloudDhcpGetallForbidden  &{Code:403 Description: Error: Message:unable to find cloud instance id for service instance 05d6bd74-b240-4544-a889-a6c18c52ade4: cloud-instance (name) 05d6bd74-b240-4544-a889-a6c18c52ade4 not found}" controller="ibmpowervscluster" …
```

Update deletion logic for VPC subnet, load balancer and PowerVS service instance

---

api/v1beta2/ibmpowervscluster_types.go
cloud/scope/powervs_cluster.go
cloud/scope/powervs_machine.go
config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclustertemplates.yaml
controllers/ibmpowervscluster_controller.go
controllers/ibmpowervsmachine_controller.go

This PR adds
- Logs wherever necessary
- Proper naming for PowerVS and VPC
- Consistent error format starting with `failed to`
- Add appropriate log levels, debug set at level 3
- Consistent naming of infra resources
Fixes #1720 
```release-note
Refactor logging
```

Refactor logging

---

metadata.yaml

Similar to this fix I opened last year: https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/1441
this can trip up parsers that read the metadata file.
Fixes #
```release-note
fix: remove trailing whitespaces from metadata.yaml
```

fix: remove whitespaces from metadata.yaml

---

.github/dependabot.yml

Currently, dependent module CAPI 1.7 and k8s 1.29 are tagged to go version 1.21. For updating the package `github.com/aquasecurity/trivy`, we need to move to go version 1.22. Until we officially move to go version 1.22, ignore updating the package.
Fixes #
```release-note
Ignore updating github.com/aquasecurity/trivy until we move to go 1.22
```

Ignore updating github.com/aquasecurity/trivy until we move to go 1.22

---

Makefile
templates/bases/powervs/kcp.yaml
templates/cluster-template-powervs-cloud-provider.yaml
templates/cluster-template-powervs-clusterclass.yaml
templates/cluster-template-powervs-clusterclass/cluster-with-kcp.yaml
templates/cluster-template-powervs.yaml
test/e2e/data/templates/cluster-template-powervs-md-remediation.yaml
test/e2e/data/templates/cluster-template-vpc.yaml

kube-vip has issues when being used with k8s 1.29. This PR fixes them by
1. From 1.29, a change has been made to `kubeadm` to provision a separate Kubeconfig file called `super-admin.conf`  and reducing the `admin.conf` User's access to the permissions provided by the cluster-admin ClusterRole. It is to be noted that in a multi-cluster setup, the `super-admin.conf` is only created on the primary control plane node, which runs `kubeadm init` is failing because kube-vip deployment is hardcoded to use `admin.conf` but kube-vip requires elevated permissions to access the API server during cluster initialization, which are available only when using the `super-admin.conf`. 
2. From 1.29, `hostAliases` do not work as expected. Add a work around to mount …

Update kube-vip spec in cluster templates to adopt k8s 1.29

---

cloud/scope/powervs_machine.go

When we are using external [cloud-provider template](https://cluster-api-ibmcloud.sigs.k8s.io/topics/powervs/external-cloud-provider) we explicitly pass the service instance id.
Internally in the code that wont be set under status field of IBMPowerVSCluster, so the in the [provider id of machine](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/e49f8ee8a7bfb2d627461f2b1e415eedbee09297/cloud/scope/powervs_machine.go#L942) the service instance will be set as empty string which is incorrect.
In this PR we try to fetch the service instance id from spec of object if its not present under the status.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) …

Fetch service instance id from spec of IBMPowerVSCluster object while setting provider id

---

cloud/scope/powervs_cluster.go
util/util.go

This PR contains changes to derive the VPC zone from the VPC region, compared to the zone derived from PowerVS region. This mitigates errors/conflicts arising where the VPC zone is different from the PowerVS zone, causing a mismatch in the CIDR.
Tests: 
The change has been tested where the compute infrastructure is provisioned in `jp-osa`, while the VPC subnet infrastructure was provisioned in `jp-tok`. The was available for use post completion of deployment.
A similar exercise was done to provision both Compute and VPC subnet in `jp-osa`. 
**Which issue(s) this PR fixes** :
Fixes #1817 
Please let me know if there are other scenarios to be covered before the changes can be merged to main. …

Derive VPC zones from VPC region instead of PowerVS region.

---

api/v1beta2/types.go
cloud/scope/powervs_cluster.go

This PR updates the log format while checking for the resource by printing the name or ID of the resource.
Fixes #
```release-note
Update log format while checking the state of a resource
```

Update log format while checking the state of a resource

---

api/v1beta2/ibmpowervscluster_webhook.go
api/v1beta2/ibmvpccluster_types.go
cloud/scope/powervs_cluster.go

Added validation for loadbalancer port against 6443 as its already used, kubebuilder tag to avoid duplicate ports and validation to avoid duplicate loadbalancer, vpcsubnet names.
Validation output:
```
The IBMPowerVSCluster "capi-powervs-keerthana" is invalid:
* spec.vpcSubnets[1]: Duplicate value: map[string]interface {}{"Name":"capi-powervs-keerthana-vpcsubnet"}
* spec.loadbalancers[2]: Duplicate value: map[string]interface {}{"Name":"capi-powervs-keerthana-loadbalancer2"}
* spec.loadbalancers[3]: Duplicate value: map[string]interface {}{"Name":"capi-powervs-keerthana-loadbalancer1"}
* spec.loadbalancers[0].additionalListeners[0].port: Invalid value: 6443: value of port should not be equal to APIServerPort (6443)
```
**Which issue(s) this PR …

Add validation for loadbalancer port against 6443 and to avoid duplicate names

---

config/manager/manager.yaml
templates/addons/crs-powervs.yaml
templates/addons/crs.yaml
templates/cluster-template-powervs-cloud-provider.yaml
templates/cluster-template-powervs-clusterclass.yaml
templates/cluster-template-powervs-create-infra.yaml
templates/cluster-template-vpc-clusterclass.yaml
templates/cluster-template.yaml
test/e2e/data/templates/cluster-template-vpc.yaml

This PR contains changes to set the TerminationMessagePolicy for controller managers to FallbackToLogsOnError
```
By setting the terminationMessagePolicy to "FallbackToLogsOnError", you can tell Kubernetes to use the last chunk of container log output if the termination message file is empty and the container exited with an error. The log output is limited to 2048 bytes or 80 lines, whichever is smaller.
```
Fixes #1767 
* Please let me know if there are other pods/containers that may need the TerminationMessagePolicy to be set. 
* The change was tested …

Set TerminationMessagePolicy to FallbackToLogsOnError

---

api/v1beta2/ibmpowervscluster_webhook.go
cloud/scope/powervs_cluster.go
cloud/scope/powervs_machine.go
cloud/scope/util.go
controllers/ibmpowervscluster_controller.go
controllers/ibmpowervsimage_controller.go
controllers/ibmpowervsmachine_controller.go
go.mod
go.sum
util/util.go

Extend existing conditions to check valid PowerVS zone and VPC region is used
Fixes #1826 
```release-note
Add webhook validation for transit gateway's global routing field
```

Add webhook validation for transit gateway's global routing field

---

cloud/scope/powervs_cluster.go
cloud/scope/types.go

Fixes #1805 
```release-note
```

Improve IBMPowerVSCluster deletion

---

Makefile
scripts/fetch_ext_bins.sh

- update kubebuilder tools to 1.28.x
Fixes #
```release-note
update kubebuilder tools to 1.28.x
```

[release-0.7]update kubebuilder tools to 1.28.x

---

api/v1beta2/ibmpowervscluster_types.go
cloud/scope/powervs_cluster.go
cloud/scope/powervs_image.go
cloud/scope/powervs_machine.go
config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclustertemplates.yaml
controllers/ibmpowervsimage_controller.go
pkg/cloud/services/resourcecontroller/resourcecontroller.go
pkg/cloud/services/resourcecontroller/service.go

Fixes #1839 
```release-note
```

Use zone to filter PowerVS service instance

---

scripts/ci-e2e.sh
test/e2e/data/templates/cluster-template-powervs-md-remediation.yaml
test/e2e/data/templates/cluster-template-powervs-md-remediation/kustomization.yaml

3CP + 1W cluster creation has been failing. 1CP and 1W are created successfully but the other 2 CP creation is not triggered due to a condition check failing on first CP
```
Machine amulya-test-control-plane-t94ht reports EtcdMemberHealthy condition is unknown (Failed to connect to the etcd pod on the amulya-test-control-plane-t94ht node: could not establish a connection to any etcd node: unable to create etcd client: context deadline exceeded)
```
On further debugging, it was discovered the nodes were not assigned IP addresses and this was due to the change introduced in https://github.com/kubernetes/kubernetes/pull/121028 in k8s v 1.29
```
NAME                              STATUS     ROLES           AGE   VERSION   INTERNAL-IP   EXTERNAL-IP …
```

Use cloud-provider template for PowerVS e2e by default

---

scripts/ci-e2e.sh

It has been observed in CI that the static pod kube-vip creation has been failing intermittently with not being able to pull the image. On further debugging, DNS resolution seemed to not be working with the name servers that were already present on the machine. Pass additional server 1.1.1.1 to the public network creation as it promises to be stable.
Fixes #
```release-note
PowerVS CI: configure public network …
```

PowerVS CI: configure public network creation with specific DNS servers

---

docs/book/src/developer/build-images.md
docs/book/src/machine-images/powervs.md

Enhance the instructions for PowerVS image build with DHCP support
Fixes #1781 
```release-note
Enhance the instructions for PowerVS image build with DHCP support
```

Enhance the instructions for PowerVS image build with DHCP support

---

cloud/scope/powervs_cluster.go
cloud/scope/powervs_cluster_test.go
controllers/ibmpowervscluster_controller.go
controllers/ibmpowervscluster_controller_test.go
pkg/cloud/services/powervs/service.go
pkg/cloud/services/resourcecontroller/service.go

1. This PR refactors the code to make use of factory functions which can be used during unit test cases for easy overriding of the function.
2. Changes are made to PowerVSClient to reuse the session or authenticator if already present in the options passed
3. Added some sample UT to demonstrate the usage of factory functions 
Fixes #
```release-note
Refactor PowerVSClusterscope function to faciliate UT integration …
```

Refactor PowerVSClusterscope function to faciliate UT integration

---

docs/book/src/user/troubleshooting.md

Update troubleshooting guide

---

cloud/scope/powervs_machine.go

**What this PR does / why we need it**: When overridding the COS endpoint in the disconnected use case, we'll need to also grab ignition from the same endpoint. This PR uses the COS endpoint override when generating the ignition config for the bootstrap machine.
Fixes #
```release-note
NONE
```

Use the COS endpoint override when generating bootstrap ignition

---

cloud/scope/vpc_cluster.go
controllers/ibmvpccluster_controller.go

Create a v2 path that will be used for the new Infrastructure implementation for VPC Clusters. All new functionality will be placed in these new v2 paths, based on the new NetworkSpec field, to prevent breaking existing implementation.
**What this PR does / why we need it**:  adds new path to fully implement VPC Cluster Infrastructure support w/o breaking current functionality
Fixes #
```release-note
adding new VPC Infrastructure pathways
```

VPC: Create v2 path for new Infrastructure implementation

---

cloud/scope/vpc_cluster.go
controllers/ibmvpccluster_controller.go
pkg/cloud/services/globaltagging/doc.go
pkg/cloud/services/globaltagging/globaltagging.go
pkg/cloud/services/globaltagging/service.go
pkg/cloud/services/resourcemanager/service.go
pkg/endpoints/endpoints.go

Add support to the v2 path to reconcile a VPC.
Includes adding GlobalTagging support, and extending ResourceManager support.
Fixes #
```release-note
extended vpc support for vpc reconcile
```

VPC: Add v2 support for VPC reconcile

---

config/manager/manager.yaml
docs/book/src/topics/powervs/clusterclass-cluster.md
docs/book/src/topics/powervs/create-resources.md
docs/book/src/topics/powervs/external-cloud-provider.md
docs/book/src/topics/vpc/load-balancer.md
main.go
pkg/options/options.go

Deprecate provider-id format v1
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/1868
```release-note
Deprecate provider-id format v1
```

Deprecate provider-id format v1

---

Makefile

This PR will print the kubebuilder asset downloaded location so developer can use to configure editors for running individual tests, For reference https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/1818
Fixes #
```release-note
None
```

Print kubebuilder assets downloaded location

---

scripts/ci-e2e.sh

Minor changes to e2e flow
Fixes #
```release-note
Minor changes to e2e flow
```

Minor changes to e2e flow

---

cloud/scope/powervs_cluster.go
controllers/ibmpowervscluster_controller.go

Fixes #1837 
With the changes, infra creation takes around ~8 mins.
Most time taking resource is DHCP server VM.
```release-note
```

Refactor infra creation to improve the overall infra setup time

---

cloud/scope/powervs_cluster.go

When an existing DHCP server is passed such as
```
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
labels:
ccm: external
cluster.x-k8s.io/cluster-name: capi-test-amulya
name: capi-test-amulya
namespace: default
spec:
clusterNetwork:
pods:
cidrBlocks:
- 192.168.0.0/16
serviceDomain: cluster.local
services:
cidrBlocks:
- 10.128.0.0/12
controlPlaneRef:
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
name: capi-test-amulya-control-plane
infrastructureRef:
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: IBMPowerVSCluster
name: capi-test-amulya
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: IBMPowerVSCluster
metadata:
annotations:
powervs.cluster.x-k8s.io/create-infra: "true"
labels: …
```

Return true when PowerVS network is already created during ReconcileNetwork

---

go.mod
go.sum

- Fix CVE-2024-6104
Fixes #
```release-note
Fix CVE-2024-6104
```

[release-0.8] Fix CVE-2024-6104

---

go.mod
go.sum

- Fix CVE-2024-6104
Fixes #
```release-note
Fix CVE-2024-6104
```

[release-0.7] Fix CVE-2024-6104

---

cloud/scope/vpc_cluster.go

Fix the references to use the cluster's name for VPC clusters.
Fixes #
```release-note
Fix cluster name references for vpc
```

Fix cluster name references

---

cloud/scope/powervs_cluster.go

#1960 
Fixes #
```release-note
```

Refactor transit gateway status

---

hack/version.sh

This PR contains a minor change to suppress a fatal warning from `git` , which is expected to be raised when make commands are used from the Development fork. The stderr is redirected to /dev/null to avoid confusion, as the error is on the expected lines that forks do not carry tags. 
Existing change: 
```
 cluster-api-provider-ibmcloud : main ✔ : ᐅ  make release
fatal: No names found, cannot describe anything.                    <--------------
RELEASE_TAG is not set
make: *** [check-release-tag] Error 1
cluster-api-provider-ibmcloud : main ✔ : ᐅ  make build
fatal: No names found, cannot describe anything.                    <--------------
make: *** No rule to make target `build'.  Stop.
```
Current change, when make release is run from …

Redirect stderr to /dev/null to suppress make command warnings.

---

docs/book/src/developer/tilt.md
go.mod
main.go

Most of the core components of cluster-api supports JSON output format for logs and capi is planning to make json output format for logs as default in future releases rather than having text output format like now. 
This PR adds support for the same in cluster-api-provider-ibmcloud repository, This will help in easy parsing of logs in obervability tools.
User needs to pass additional flag `--logging-format=json ` to set the output log format to JSON
Default text format log output
```
I0923 08:58:50.656130       1 reflector.go:302] Stopping reflector *v1beta2.IBMVPCMachineTemplate (10m27.692803049s) from pkg/mod/k8s.io/client-go@v0.30.3/tools/cache/reflector.go:232
I0923 08:58:50.660508       1 reflector.go:302] Stopping reflector …
```

Add support for JSON output format for logs

---

api/v1beta2/types.go
cloud/scope/vpc_cluster.go
controllers/ibmvpccluster_controller.go
pkg/cloud/services/vpc/mock/vpc_generated.go
pkg/cloud/services/vpc/service.go
pkg/cloud/services/vpc/vpc.go

Add support to reoncile VPC subnets for the new v2 VPC Infrastructure reoncile logic.
Related: https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/1896
**What this PR does / why we need it**:  
Add new support for reconciling VPC subnets for VPC Infra
Fixes #
**Release note**:  
```release-note
Add support to new (v2) reconciliation of Subnets for VPC Infrastructure
```

VPC: Add subnet reconciliation

---

docs/book/book.toml

This would beautify the meeting notes link. Like below
1. Existing way: https://docs.google.com/document/d/1oWnqXy1VFv0E3kovQoZfS6IlVP0L4eaQsN-2HYC_6_A
2. New way:  https://cluster-api-ibmcloud.sigs.k8s.io/agenda.html
Reference: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/2125/files
Fixes #
```release-note
None
```

Add redirect url for meeting document

---

api/v1beta2/ibmpowervscluster_webhook.go
cloud/scope/powervs_cluster.go
cloud/scope/powervs_cluster_test.go
controllers/ibmpowervscluster_controller.go

**This PR refactors the reconciliation of resources to follow a unit format as below**
1. Fetch ID from IBMPowerVSCluster status object. If ID exists, check the status of the resource in cloud and return
2. If ID is not present in the status, try to fetch it from the IBMPowerVSCluster spec and check if the resource exists in cloud. Here we can check either via name or ID passed in the spec. If resource with given ID doesn't exist, return err, or else check the status of the resource in cloud and set IBMPowerVSCluster.status accordingly
3. If resource with given name doesn't exist, proceed with creating the resource. If it exists, check the status of the resource in cloud. Set IBMPowerVSCluster.status accordingly in both cases
**The changes in this …

Refactor reconcilation of resources

---

cloud/scope/powervs_cluster.go
cloud/scope/vpc_cluster.go
controllers/ibmvpccluster_controller.go
pkg/cloud/services/vpc/mock/vpc_generated.go
pkg/cloud/services/vpc/service.go
pkg/cloud/services/vpc/vpc.go

Fixes #
```release-note
Add reconciliation support for extended VPC Security Groups
```

VPC: Extend support for SG's

---

cloud/scope/powervs_machine.go
controllers/ibmpowervsmachine_controller.go
controllers/ibmpowervsmachine_controller_test.go

**What this PR does / why we need it**:  
1. Adds UTs to cover existing reconcile operations of VPC loadbalancer pool member creation
2. Adds check to ensure Loadbalancer back-end pool is only for controlplane machines
Fixes #1990

Configure Loadbalancer back-end pool only for controlplane machines

---

cloud/scope/powervs_cluster_test.go

Add UT for ReconcileNetwork, getNetwork, isDHCPServerActive, checkDHCPServerStatus & createDHCPServer function
Partially fixes https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/1818

Add UT for ReconcileNetwork and its subfunctions

---

cloud/scope/powervs_cluster.go

Need to depend on load balancer's state to set the cluster's ready status instead of using requeue logic which is designed to block the reconciliation.
Fixes #2026 
```release-note
```

Fix PowerVS cluster's load balancer status check

---

controllers/ibmpowervscluster_controller.go
controllers/ibmpowervsmachine_controller.go
main.go

This PR adds support for pausing a cluster reconcilation, to facilitate that it adds event filters and predicates while setting up the controller.
Fixes #https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/1730
```release-note
Add support for pausing IBMPowerVSCluster and IBMPowerVSMachine reconcilation
```

Add support for pausing cluster reconcilation

---

api/v1beta2/ibmpowervscluster_webhook.go

This PR contains changes to avoid webhook panic
Before change
```
$ cat template.yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: IBMPowerVSCluster
metadata:
annotations:
powervs.cluster.x-k8s.io/create-infra: "true"
labels:
cluster.x-k8s.io/cluster-name: capi-powervs-karthik-two
name: capi-powervs-karthik-two
namespace: default
spec:
serviceInstance:
name: capi-powervs-karthik-two-serviceInstance
$ kubectl create -f template.yaml
Error from server (InternalError): error when creating "/Users/karthikkn/karthik-k8-workspace/cluster-api-provider-ibmcloud/templates/new.yaml": Internal error occurred: failed calling webhook "vibmpowervscluster.kb.io": failed to call webhook: Post "https://capi-ibmcloud-webhook-service.capi-ibmcloud-system.s …
```

Fix webhook panic when VPC is nil in IBMPowerVSCluster spec

---

cloud/scope/powervs_machine.go
controllers/ibmpowervsmachine_controller.go
controllers/ibmpowervsmachine_controller_test.go

This PR allows to create cos bucket and push ignition data to it only when IBMPowerVSCluster.Spec.Ignition is set because COS Instance is created only when this is [set](https://github.com/Karthik-K-N/cluster-api-provider-ibmcloud/blob/2a3745effaed2d825024566f8f876a3f25d8127f/controllers/ibmpowervscluster_controller.go#L311-L318).
Even if user data format is ignition and IBMPowerVSCluster.Spec.Ignition is nil, the code will eventually fail to [fetch cos ](https://github.com/Karthik-K-N/cluster-api-provider-ibmcloud/blob/5e43c6e5df57581d724dc70f49db76506f91a2c5/cloud/scope/powervs_machine.go#L584-L588)instance as it might not be created.
Removed create infra anotation checks in machine controller as it might not needed.
**Which issue(s) this PR …

Use ignition only when Ignition is set in IBMPowerVSCluster

---

cloud/scope/powervs_machine.go
controllers/ibmpowervsmachine_controller.go
controllers/ibmpowervsmachine_controller_test.go

This PR modifies the logic around setting provider id.
There were many instances where provider id was not set properly and the cluster creation was not successfull. Main reason for that is service instance id being set empty.
Made changes to fetch service instance id from name if id not found in spec or status. This case will occur mainly when cluster is reconciled by external controller.
Made changes to return error instead of empty string in case of not able to find service instance id.
Fixes #
1. Please confirm that if this PR …

Explicitly return error incase of not able to set provider id in correct format

---

cloud/scope/powervs_cluster.go
controllers/ibmpowervscluster_controller_test.go
go.mod

Fixes # Related to https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/1818
```release-note
```

Improve UT coverage for IBMPowerVSCluster controller

---

.gitignore
cloud/scope/powervs_cluster_test.go

**What this PR does / why we need it**: Adds UT for ReconcileLoadBalancers function
Fixes # https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/1818
```release-note
```

Adds UT for ReconcileLoadBalancers function

---

controllers/ibmpowervscluster_controller.go
controllers/ibmpowervscluster_controller_test.go

Adds UT for reconcile delete functionality 
Partially Fixes https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/1818
```release-note
```

Add UT for reconcileDelete function

---

cloud/scope/powervs_cluster_test.go

This PR covers UT for deleteTransitGatewayConnections, DeleteDHCPServer, DeleteServiceInstance, DeleteCOSInstance, isResourceCreatedByController functions
Fixes #1818 
```release-note
```

Improve UT coverage for IBMPowerVSCluster deletion flow

---

api/v1beta2/types.go
cloud/scope/vpc_cluster.go
controllers/ibmvpccluster_controller.go

**What this PR does / why we need it**:  Add support to reconcile extended VPC Load Balancers
Fixes #
```release-note
Add reconciliation support for extended VPC Load Balancer definitions
```

Vpc reconcile lbs

---

cloud/scope/powervs_cluster_test.go

UT for ReconcileCOSInstance functionality
Fixes # Part of https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/1818
```release-note
```

UT for ReconcileCOSInstance functionality

---

cloud/scope/powervs_cluster.go
cloud/scope/powervs_cluster_test.go

Add UTs for ReconcileVPCSecurityGroups function and fixes minor bug found during writing UTs
Fixes #
```release-note
Add UT for ReconcileVPCSecurityGroups function
```

Add UT for ReconcileVPCSecurityGroups function

---

controllers/ibmpowervsimage_controller.go

When an image is associated to a externally managed cluster, during deletion there might be a chance where cluster resource might have already cleaned up So get cluster only when image is not deleted
Fixes #
```release-note
Handle externally managed cluster's image deletion 
```

Handle external managed cluster's image deletion

---

cloud/scope/powervs_cluster.go
cloud/scope/powervs_cluster_test.go
controllers/ibmpowervscluster_controller.go
controllers/ibmpowervscluster_controller_test.go

- If only IBMPowerVSCluster.Spec.Network is set, network would be validated and if exists already will get used as cluster’s network or a new network will be created via DHCP service.
- If only IBMPowerVSCluster.Spec.DHCPServer is set, DHCP server would be validated and if exists already, will use DHCP server’s network as cluster network. If not a new DHCP service will be created and it’s network will be used.
- If both IBMPowerVSCluster.Spec.Network & IBMPowerVSCluster.Spec.DHCPServer is set, network and DHCP server would be validated and if both exists already then network is belongs to given DHCP server or not would be validated.
- If both IBMPowerVSCluster.Spec.Network & IBMPowerVSCluster.Spec.DHCPServer is not set, by default DHCP service will …

Refactor ReconcileNetwork

---

cloud/scope/powervs_cluster.go
cloud/scope/powervs_cluster_test.go
controllers/ibmpowervscluster_controller_test.go
pkg/cloud/services/vpc/mock/vpc_generated.go
pkg/cloud/services/vpc/service.go
pkg/cloud/services/vpc/vpc.go

Currently when there are multiple subnets specified, it uses the first available vpcZone for all subnets by default and as a result, there is a clash in the CIDR. Hence added logic to use the subsequent vpcZones for the subnets.
If there are multiple subnets provided than the available vpcZones, the zones are selected based on round robin method.
This PR contains change to use vpcSubnetIPAddressCount, where when two subnets are to be created in the same zone, the subnets are created with the next available address prefix based on the vpcSubnetIPAddressCount.
Taking one of the below examples for reference
```
- name: subnet-1
zone: eu-es-2
- name: subnet-2
- name: subnet-3
- name: subnet-4
- name: subnet-5
zone: eu-es-2
- name: subnet-6
zone: eu-es-1 …
```

Use multiple zones in case of multiple subnets

---

hack/tools/go.mod

**What this PR does / why we need it**: Fixes the lint failure here: https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/2071
This is happening because dependabot does not update the go.mod version automatically and our CI checks that running `go mod tidy` does not make any further changes to the go.mod file. The version change is happening because go-lint depends on version 1.22.1 which is due to this dependency in go-lint: honnef.co/go/tools
Fixes # …

Bumped go.mod version in tools

---

controllers/ibmpowervscluster_controller_test.go

The issue was when we try to compare the aggregated errors, the Equal function in Expect expects the errors be in order. But since the VPC and PowerVS reconcilers are called in goroutine, we can never know the order of completion. So replaced Equal with ConsistOf function which ignores the order and just checks if the errors exist. 
Since the actual errors can be a simple error / aggregate error, added a condition to assert based on the error type.
Fixes #2097 
1. Please confirm that if this PR changes any image versions, then that's …

Modify the expect check for aggregate errors

---

cloudbuild.yaml

- bump gcr.io/k8s-staging-test-infra/gcb-docker-gcloud to v20241229-5dc092c636
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/2119
```release-note
bump gcr.io/k8s-staging-test-infra/gcb-docker-gcloud to v20241229-5dc092c636
```

bump gcr.io/k8s-staging-test-infra/gcb-docker-gcloud to v20241229-5dc092c636

---

.github/workflows/weekly-security-scan.yaml

- Pin workflow to run on ubuntu-24.04
- This will also fix the warnings seen on GH Actions UI under scan workflow results
Fixes #2127 
```release-note
Pin workflow to run on ubuntu-24.04
```

Pin workflow to run on ubuntu-24.04

---

config/crd/kustomization.yaml
config/default/kustomization.yaml
test/e2e/data/templates/cluster-template-powervs-md-remediation/kustomization.yaml

**What this PR does / why we need it**: Fix Warnings in Kustomization file
`make release
`
```
```
Description:
1. Replace bases with resources
Diff:
bases (deprecated): This field was used to reference other directories or resources (e.g., CRDs, namespaces, etc.) as "bases" from which resources would be pulled.
resources (recommended): The resources field is now used to include external files or resources directly. Kustomize now uses resources instead of bases for the same purpose.
Migration Approach:
Replacing the bases field with resources, using the same paths.
Before:
```
bases:
- ../crd
- ../rbac
```
After:
```
resources:
- ../crd
- ../rbac
```
2. Replace commonLabels with labels
Diff:
commonLabels (deprecated): The commonLabels field was used to apply common labels to all resources …

Fix warnings in kustomization file

---

cloud/scope/vpc_cluster.go

Fix bug where an existing VPC ID that was found, was not being returned, resulting in attempts to recreate the VPC.
Related: https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/2140
Resolves 2140
Fixes #
```release-note
Fix bug when an existing vpc is provided for IBM Cloud Infrastructure but attempts are still made to create it 
```

BUG: IBM Cloud Infra: Return existing VPC ID

---

api/v1beta2/types.go

Make sure that the optional fields for the
VPCMachinePlacementTarget definition are configured properly for JSON serialization.
Related: https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/2150
Fixes bug with Infrastructure Machines attempting to use Dedicated Host support
Fixes #2150 
```release-note
Fix bug with placementTarget.dedicatedHostGroup field being omitted when no provided
```

Infrastructure: Fix machine placement target defaults

---

Makefile
hack/ccm/Makefile
netlify.toml

- bump golang to v1.22.11
- fix security scan vulnerabilities
Fixes #
```release-note
bump golang to v1.22.11
```

bump golang to v1.22.11

---

Makefile
hack/ccm/Makefile
netlify.toml

- Bump golang to v1.22.11
- Fix security scan vulnerabilities
Fixes #
```release-note
Bump golang to v1.22.11
```

[release-0.9] Bump golang to v1.22.11

---

docs/proposal/additional-disks.md

Adds a proposed for resolving #1920
Fixes #
```release-note
```

Proposal for adding Additional Disks to node

---

.golangci.yml

- fix linters related warnings
```
WARN [config_reader] The configuration option `run.skip-files` is deprecated, please use `issues.exclude-files`. 
WARN [config_reader] The configuration option `linters.staticcheck.go` is deprecated, please use global `run.go`. 
WARN [config_reader] The configuration option `linters.stylecheck.go` is deprecated, please use global `run.go`. 
WARN The linter 'execinquery' is deprecated (since v1.58.0) due to: The repository of the linter has been archived by the owner.
```
Fixes #
1. Please confirm that …

fix linters related warnings

---

cloud/scope/machine_test.go

This PR refactor the code to parse token and get accountID and adds the coverage for setProviderID function
Fixes # https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/2128
```release-note
Add uts for setProviderID
```

Add uts for setProviderID

---

docs/book/src/developer/e2e.md
docs/book/src/developer/tilt.md
docs/book/src/topics/powervs/creating-a-cluster.md
docs/book/src/topics/vpc/creating-a-cluster.md
docs/book/src/user/troubleshooting.md

**What this PR does / why we need it**: This PR contains documentation changes which were out of place for project local setup which includes broken links and some missing information.  
Fixes #
```release-note
none
```

Enhance local development documentation

---

hack/ccm/Makefile

- fix powervs_cloud_controller image build
Fixes #2176 
```release-note
fix powervs_cloud_controller image build
```

fix powervs_cloud_controller image build

---

docs/book/src/machine-images/vpc.md
scripts/ci-e2e.sh
test/e2e/config/ibmcloud-e2e-vpc.yaml

**What this PR does / why we need it**: Bump VPC CI to k8s v1.31
Fixes #

Build and publish vpc image for k8s version 1.31.4

---

cloud/scope/machine.go

Fix the Infrastructure Machine management for Global Tagging service and endpoints.
Related: https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/2231
Fixes Infrastructure Machine endpoint override for GlobalTagging
Fixes #2231 
```release-note
fix globaltagging endpoint override for infrastructure machines
```

Infra: Fix Machine GT endpoint management

---

docs/book/src/machine-images/vpc.md
scripts/ci-e2e.sh
test/e2e/config/ibmcloud-e2e-vpc.yaml

**What this PR does / why we need it**: Bump VPC CI to k8s v1.30
Fixes #2084 
**Testing**
Deployed a cluster using this image
```release-note
```

Build and publish vpc image for k8s version 1.30.4

---

cloudbuild.yaml

- Bump gcb-docker-gcloud to v20241229-5dc092c636
Fixes #2261 
```release-note
Bump gcb-docker-gcloud to v20241229-5dc092c636
```

Bump gcb-docker-gcloud to v20241229-5dc092c636

---

docs/book/src/topics/powervs/creating-a-cluster.md
docs/book/src/topics/vpc/creating-a-cluster.md

This PR adds details for  environment variables for  VPC and PowerVS in CAPIBM book
Fixes: https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/2133
```release-note
Add reference  links for environment variables for  VPC and PowerVS
```

Add reference  links for environment variables for  VPC and PowerVS

---

Makefile

- fix release-manifests target
Fixes #2192 
```release-note
fix release-manifests target
```

fix release-manifests target

---

api/v1beta2/ibmpowervscluster_webhook.go
api/v1beta2/ibmpowervsclustertemplate_webhook.go
api/v1beta2/ibmpowervsclustertemplate_webhook_test.go
api/v1beta2/ibmpowervsimage_webhook.go
api/v1beta2/ibmpowervsmachine_webhook.go
api/v1beta2/ibmpowervsmachine_webhook_test.go
api/v1beta2/ibmpowervsmachinetemplate_webhook.go
api/v1beta2/ibmpowervsmachinetemplate_webhook_test.go
api/v1beta2/ibmvpccluster_webhook.go
api/v1beta2/ibmvpcmachine_webhook.go
api/v1beta2/ibmvpcmachine_webhook_test.go
api/v1beta2/ibmvpcmachinetemplate_webhook.go
api/v1beta2/ibmvpcmachinetemplate_webhook_test.go

PR removes the deprecated webhook interfaces and adds CustomValidator.
Fixes #2288
```release-note
Remove usage of deprecated webhook admission and validation interfaces
```

Remove deprecated admission interfaces

---

templates/addons/crs-powervs.yaml
templates/addons/crs.yaml
templates/cluster-template-powervs-clusterclass.yaml
templates/cluster-template-powervs-create-infra.yaml
templates/cluster-template-powervs.yaml
templates/cluster-template-vpc-clusterclass.yaml
templates/cluster-template.yaml
test/e2e/data/templates/cluster-template-powervs-md-remediation.yaml
test/e2e/data/templates/cluster-template-vpc.yaml

- generate templates pointing to `registry.k8s.io`
Fixes #2291 
```release-note
generate templates pointing to registry.k8s.io
```

generate templates pointing to registry.k8s.io

---

api/v1beta2/groupversion_info.go
api/v1beta2/ibmpowervscluster_types.go
api/v1beta2/ibmpowervsclustertemplate_types.go
api/v1beta2/ibmpowervsimage_types.go
api/v1beta2/ibmpowervsmachine_types.go
api/v1beta2/ibmpowervsmachinetemplate_types.go
api/v1beta2/ibmvpccluster_types.go
api/v1beta2/ibmvpcclustertemplate_types.go
api/v1beta2/ibmvpcmachine_types.go
api/v1beta2/ibmvpcmachinetemplate_types.go

Its a work towards #2286 , This PR changes the scheme registration for API types.
Fixes #
```release-note
```

Move away from use of controller-runtime scheme while registering api types

---

Dockerfile
cloud/scope/powervs_machine.go
cloud/scope/suite_test.go
controllers/suite_test.go
internal/webhooks/common.go
internal/webhooks/common_test.go
internal/webhooks/doc.go
internal/webhooks/ibmpowervscluster.go
internal/webhooks/ibmpowervscluster_test.go
internal/webhooks/ibmpowervsclustertemplate.go
internal/webhooks/ibmpowervsclustertemplate_test.go
internal/webhooks/ibmpowervsimage.go
internal/webhooks/ibmpowervsmachine.go
internal/webhooks/ibmpowervsmachine_test.go
internal/webhooks/ibmpowervsmachinetemplate.go
internal/webhooks/ibmpowervsmachinetemplate_test.go
internal/webhooks/ibmvpccluster.go
internal/webhooks/ibmvpcmachine.go
internal/webhooks/ibmvpcmachine_test.go
internal/webhooks/ibmvpcmachinetemplate.go
internal/webhooks/ibmvpcmachinetemplate_test.go
internal/webhooks/suite_test.go
internal/webhooks/util.go
main.go

Its a work towards https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/2286
This PR moves the webhooks from api directory to separate webhooks directory.
Fixes #
```release-note
Move webhooks out of api directory.
```

Move wehbooks out of api directory to seperate directory

---

cloud/scope/machine.go

Fixes #2260 
```release-note
Fixed bug where adding volume name with multiple worker nodes would cause errors due to unique volume name constraint.
```

Fixed bootVolume name bug

---

api/v1beta2/ibmpowervsmachine_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachinetemplates.yaml
go.mod
go.sum

This PR fixes https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/2167
The respective PR for powervs-utils is merged: https://github.com/ppc64le-cloud/powervs-utils/pull/18

Add the e1050 System Type

---

test/e2e/e2e_test.go

Add Kubeconfig and Cluster config path while deleting the cluster in e2e
Fixes part of #2307
```release-note
Add Kubeconfig and Cluster config path while deleting the cluster in e2e
```

Add kubeconfig and cluster config path while deleting the cluster in e2e

---

templates/addons/crs-powervs.yaml
templates/addons/crs.yaml
templates/cluster-template-powervs-clusterclass.yaml
templates/cluster-template-powervs-create-infra.yaml
templates/cluster-template-powervs.yaml
templates/cluster-template-vpc-clusterclass.yaml
templates/cluster-template.yaml
test/e2e/data/templates/cluster-template-powervs-md-remediation.yaml
test/e2e/data/templates/cluster-template-vpc.yaml

Updates the cloud-controller-manager container image to latest image
Image built via PR: https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/2314
Image promotion is done via PR: https://github.com/kubernetes/k8s.io/pull/8013
Image location: https://console.cloud.google.com/artifacts/docker/k8s-staging-capi-ibmcloud/us/gcr.io/powervs-cloud-controller-manager
Fixes #
```release-note
Update …
```

Update cloud-controller-manager container image to latest image

---

Makefile

The e2e test suite creates 2 clusters. Since clutser-api has been bumped, the e2e has been failing with conflicts such as subnet creation in VPC because 2 cluster creations are being triggered simutlaneously. Run the tests serially to fix it.
Fixes part of #2307
```release-note
Change the number of ginkgo nodes to 1 to run the e2e tests serially
```

Change the number of ginkgo nodes to 1 to run the e2e tests serially

---

templates/cluster-template.yaml
templates/cluster-template/md.yaml
test/e2e/data/templates/cluster-template-vpc.yaml

**What this PR does / why we need it**: 
The iops given in the additionalvolumes fields in e2e template is invalid, this PR fixes that.
Fixes #
```release-note
Fixed additionalvolume fields in e2e template
```

Fixed additionalvolume fields in e2e template

---

main.go

Fixes #2148 
```release-note
```

Added flag to disable http/2

---

api/v1beta2/ibmpowervscluster_types.go
cloud/scope/powervs_cluster.go
cloud/scope/powervs_cluster_test.go
config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclustertemplates.yaml
internal/webhooks/ibmpowervscluster.go
internal/webhooks/ibmpowervscluster_test.go

Fix priority between network and DHCP server
Do not allow to set both network and DHCP server details which will create conflict while creating new DHCP server on whether to use network name or DHCP server name
Fixes #2159 
```release-note
Fix priority between network and DHCP server
```

Fix priority between network and DHCP server

---

cloud/scope/powervs_cluster.go
cloud/scope/powervs_cluster_test.go
cloud/scope/powervs_machine.go
pkg/cloud/services/cos/service.go

This PR adds the missing UT to ReconcileServiceInstance method by adding ability to override the COSClient.
Fixes #https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/2034
```release-note
Enhance UT for ReconcileCOSInstance method
```

Enhance UT for ReconcileCOSInstance method

---

.trivyignore
Makefile
netlify.toml

- bump go to 1.23.8 and add CVEs to trivyignore
The [weekly security scan task](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/actions/workflows/weekly-security-scan.yaml) has found two modules that have CVEs in our codebase.
- golang.org/x/crypto
- golang.org/x/net
To bump these to the fixed version (0.35 for crypto and 0.38 for net), we would need to bump the project to use 1.23. We don't generally do this as it'd force anyone consuming the module downstream to upgrade their go as well and that might not work for their projects or timelines. (Hence ignoring those explicitly) …

[release-0.10] bump go to 1.23.8 and add CVEs to trivyignore

---

RELEASE.md
docs/book/src/developer/release.md

This PR captures additional information associated with the release-process.
This is a initial set of steps identified for the release process. Please let me know if any section needs elaboration.
```release-note
Update documentation for release process
```

Update documentation for release process

---

test/e2e/config/ibmcloud-e2e-powervs.yaml
test/e2e/config/ibmcloud-e2e-vpc.yaml
test/e2e/data/shared/metadata.yaml

Update cluster-api version to v1.11.x in e2e test files
Fixes part of #2387 
```release-note
Update cluster-api version to v1.11.x in e2e test files
```

Update cluster-api version to v1.11.0-alpha.0 in e2e test files

---

Makefile

- Verify generation of e2e templates as a part of make generate target in favour of catching error such as one mentioned in #2394 
- The check to conditionally generate the e2e templates has been removed to keep it simple and help with verification
Fixes #
```release-note
Verify generation of e2e templates as a part of make generate target
```

Verify generation of e2e templates as a part of make generate target

---

templates/bases/powervs/cluster.yaml
templates/bases/powervs/kcp.yaml
templates/bases/powervs/kubeadm-config.yaml
templates/bases/powervs/md.yaml
templates/bases/vpc/cluster.yaml
templates/bases/vpc/kcp.yaml
templates/bases/vpc/md.yaml
templates/cluster-template-powervs-clusterclass.yaml
templates/cluster-template-powervs-clusterclass/cluster-with-kcp.yaml
templates/cluster-template-powervs-clusterclass/md.yaml
templates/cluster-template-powervs-create-infra.yaml
templates/cluster-template-powervs.yaml
templates/cluster-template-vpc-clusterclass.yaml
templates/cluster-template-vpc-clusterclass/cluster-with-kcp.yaml
templates/cluster-template-vpc-clusterclass/md.yaml
templates/cluster-template.yaml
test/e2e/data/templates/cluster-template-powervs-md-remediation.yaml
test/e2e/data/templates/cluster-template-vpc.yaml

Update the cluster templates with the latest changes added in cluster-api version 1.11.0-alpha.2
errors on template deployment
```
Error from server (BadRequest): error when creating "first.yaml": Cluster in version "v1beta2" cannot be handled as a Cluster: strict decoding error: unknown field "spec.controlPlaneRef.apiVersion", unknown field "spec.infrastructureRef.apiVersion"
Error from server (BadRequest): error when creating "first.yaml": KubeadmControlPlane in version "v1beta2" cannot be handled as a KubeadmControlPlane: strict decoding error: unknown field "spec.machineTemplate.infrastructureRef.apiVersion"
Error from server (BadRequest): error when creating "first.yaml": MachineDeployment in version "v1beta2" cannot be handled as a …
```

Update the cluster templates with the latest changes added in cluster-api version 1.11.0-alpha.2

---

templates/cluster-template-powervs-clusterclass.yaml
templates/cluster-template-powervs-clusterclass/cluster-with-kcp.yaml
templates/cluster-template-powervs-create-infra.yaml
templates/cluster-template-powervs.yaml
templates/cluster-template-powervs/kcp.yaml
templates/cluster-template-vpc-clusterclass.yaml
templates/cluster-template-vpc-clusterclass/cluster-with-kcp.yaml
templates/cluster-template.yaml
templates/cluster-template/kcp.yaml
test/e2e/data/templates/cluster-template-powervs-md-remediation.yaml
test/e2e/data/templates/cluster-template-vpc.yaml

Since the flag is not supported, setting this flag in v1.33 leads to apiserver not starting as unknown flag error.
K8s reference: https://github.com/kubernetes/kubernetes/pull/130162
Fixes # part of #2416
```release-note
Remove apiserver cloud-provider: external flag as its removed in k8s v1.33
```

🌱  Remove external cloud-provider flag from apiserver as its removed in k8s v1.33

---

templates/bases/vpc/kcp.yaml
templates/cluster-template-vpc-clusterclass.yaml
templates/cluster-template-vpc-clusterclass/cluster-with-kcp.yaml
templates/cluster-template.yaml
test/e2e/data/templates/cluster-template-vpc.yaml

VPC cluster deployment is failing with below error after cluster-api version update to 1.11.0-beta.0
```
KubeadmControlPlane.controlplane.cluster.x-k8s.io "capibm-e2e-4cosq8-control-plane" is invalid: [spec.kubeadmConfigSpec.clusterConfiguration.dns: Invalid value: 0: spec.kubeadmConfigSpec.clusterConfiguration.dns in body should have at least 1 properties, spec.kubeadmConfigSpec.clusterConfiguration.scheduler: Invalid value: 0: spec.kubeadmConfigSpec.clusterConfiguration.scheduler in body should have at least 1 properties, spec.kubeadmConfigSpec.clusterConfiguration.etcd: Invalid value: 0: spec.kubeadmConfigSpec.clusterConfiguration.etcd in body should have at least 1 properties, spec.kubeadmConfigSpec.joinConfiguration.discovery: Invalid value: 0: …
```

Fix VPC cluster templates post CAPI version bump to v1.11.0-beta.0

---

controllers/ibmvpccluster_controller.go

.This PR fixes the cluster deletion flow by removing the finalizer and logging about the non implementation instead of returning an error which causes the deletion to be stuck indefinitely.
Fixes #2442 
```release-note
Fix VPC cluster reconcileV2 delete flow
```

Fix VPC cluster reconcileV2 delete flow

---

docs/book/src/machine-images/vpc.md
scripts/ci-e2e.sh
test/e2e/config/ibmcloud-e2e-vpc.yaml

Bump VPC CI image to v1.33.0
Fixes #
```release-note
Bump VPC CI image to v1.33.0
```

Bump VPC CI image to v1.33.0

---

hack/boskos.sh
scripts/ci-e2e.sh

Minor updates to ci-e2e.sh such as renaming environment variables and exporting necessary boskos data according to the job type.
Fixes #
```release-note
Minor updates to ci-e2e.sh
```

Minor updates to ci-e2e.sh

---

.github/ISSUE_TEMPLATE/release.md
docs/book/src/topics/capibmadm/index.md
docs/book/theme/css/custom.css
hack/tools/tools.go

- formatted capibmadm installation instructions.
- Modified release checklist to include a section about updating the capibmadm tool version after every new release.
**Which issue(s) this PR fixes:**
Fixes #2367
```
updated capibmadm cli tool installation guide
```

Update capibmadm cli tool installation guide
